### ISSUE TITLE
[Documentation] Accessibility

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#111]
Some inspiration, if you have not seen it yet. I think HeadlessUI did a pretty good Job explaining how accessibility works in a concrete and visually easy adaptive way.

https://headlessui.com/react/tabs#accessibility-notes

Maybe you want to adapt this in your docs

**Comment by blvdmitry** [comment]
Components now have a section explaining their shortcuts and still have accessibility information when relevant, so closing this
