### ISSUE TITLE
Icons from docs somewhere provided? 

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#114]
The Icons that are used through out the documentation - are they provided from your side somewhere? Tried to import it from `Reshaped` but didn't worked.

I think this would help for faster development, if the Icons from docs could be made available. So you can reference it in the docs, and the user can simply copy paste the code.

So no need to go first to an online icon library, searching for the right icon. Downloading it. Uploading it to my Bucket/Repository and then finally using it.

**Comment by blvdmitry** [comment]
These icons are coming from the website and we don't export anything of ours for that. We do you use https://feathericons.com a lot though, I think there was also an npm package to get them directly

**Comment by mmailaender** [comment]
There are two
Simple SVG:
https://www.npmjs.com/package/feather-icons
As react component: https://www.npmjs.com/package/feather-icons-react 


Maybe you can think about referencing that throughout the installation part. 

```
npm install ./reshaped.tgz

// optional
npm install feather-icons
```

Giving your users the possibility to copy, paste and run your code without the need of adjustments is in my opinions a really powerful feature.

**Comment by blvdmitry** [comment]
Took me quite some time to finally get here, but I've added a new section in the docs for 2.11 after testing react-feather in the blog starter:
https://github.com/formaat-design/reshaped-blog-starter/blob/main/src/config.ts

<img width="803" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/713441a0-7f0a-4f94-8ebc-d6bae71e0dee">
