### ISSUE TITLE
Align child elements of different blocks

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#119]
Is there a way in Reshaped to achieve this?

https://stackoverflow.com/questions/56711501/align-child-elements-of-different-blocks

**Comment by blvdmitry** [comment]
We currently don't have to do it in exactly this way. For some cases, it's possible to achieve similar with View but for actual grid functionality, I would suggest using css grid directly for now

**Comment by blvdmitry** [comment]
After looking into multiple potential component options, I think it should be easier to have specific CSS grid and subgrid implementation on the product side. Grid is a modern API so it doesn't have gotchas that we could resolve out of the box, while providing it as a component would mean that we'll have to inline templates as css variables, basically asking you to write the same code as you would write in your css. Therefore I'll close this issue for now, until we have any radical changes in our css setup, that would allow us to have access to the css build process and optimise this code.
