### ISSUE TITLE
[Feature Request] Code Component

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#140]
Like Mantine is providing a code component https://mantine.dev/core/code/ (It would be great to skip the step of installing a 3rd party library (simpler and faster to use))

It could be maybe a variant of <Text> and could be developed in two stages:
v1 having, e.g., monospace as a font (Most essential for us - For static text, we could improvise with the <Text> color property) 
v2 having Syntax highlighting

Having it out of the box in Reshaped would make it a 5-minute task to integrate visual code.

**Comment by blvdmitry** [comment]
Closing as out of scope for now
