### ISSUE TITLE
[Feature Request] <KBD> Keyboard Component

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#142]
Component to easily show Keyboard shortcuts on Actions like Buttons etc.

https://mantine.dev/core/kbd/
https://flowbite.com/docs/components/kbd/
https://daisyui.com/components/kbd/

**Comment by blvdmitry** [comment]
Coming in the next nightly release later this week
<img width="822" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/c4d147d5-94f6-4501-a1cb-938b31a710c6">
