### ISSUE TITLE
Prettier plugin

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#145]
Prettier plugin for automatic prop sorting (like the [tailwind prettier plugin](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier))

This would increase the readability of code.

**Comment by blvdmitry** [comment]
JSX prop sorting involves a lot of AST logic which will be considerably more complicated than just sorting classnames within a string. Therefore I'm not planning to implement this within the package but it still can be implemented by the community
