### ISSUE TITLE
[Feature Request] Add a file uploading component

### ISSUE THREAD

**Issue by X86-7** [formaat-design/reshaped#146]
I think a great addition to Reshaped would be to add a file-uploading component. 

Something similar to this

![image](https://user-images.githubusercontent.com/84218614/226207588-e1283065-1ab1-434a-95dd-a13e52033101.png)

I think adding the ability to change the text under to specify what files can be accepted would be sweet.

**Comment by blvdmitry** [comment]
Amazing, thanks for adding it here

**Comment by its-monotype** [comment]
Would be also great to have ability to integrate it with react-dropzone

**Comment by blvdmitry** [comment]
Testing out some examples, component is responsible just for the drop area, previews are custom here 

https://github.com/formaat-design/reshaped/assets/887379/6587e208-3351-4115-8287-aa4f8fa3318f

**Comment by X86-7** [comment]
Looks awesome! What are you using to show the custom uploaded views?

**Comment by blvdmitry** [comment]
These are completely custom so it can be integrated with any library. Here is the code I currently have in my story (I was a bit lazy moving css out in a separate file for testing):

```tsx

const Demo = () => {
	const [files, setFiles] = React.useState<File[]>([]);

	return (
		<View gap={2}>
			<style>
				{`
				@keyframes heightBounce {
					0% { height: 0; }
					70% { height: 70px; }
					100% { height: 60px; }
			}
			
			.element {
					overflow: hidden; 
					height: 0; 
					animation: heightBounce 0.3s ease-out forwards;
					translate: transformZ(0);
			}
			`}
			</style>
			<FileUpload
				name="file"
				icon={IconZap}
				onChange={(args) => setFiles((prev) => [...prev, ...args.value])}
				inputAttributes={{ multiple: true }}
			>
				<div>
					Drop files to attach, or <Link variant="plain">browse</Link>
				</div>
			</FileUpload>
			<View paddingBottom={20}>
				<View gap={2} direction="row" position="absolute">
					{files &&
						Array.from(files).map((file) => {
							return (
								<Image
									key={file.name}
									src={URL.createObjectURL(file)}
									width="60px"
									borderRadius="small"
									className="element"
								/>
							);
						})}
				</View>
			</View>
		</View>
	);
};
```

**Comment by X86-7** [comment]
Would it be possible to perhaps make the border primary color when hovering objects over? Interested to see what it would look like

**Comment by blvdmitry** [comment]
react-dropzone seems to be working nicely as well:

```tsx
const onDrop = React.useCallback((acceptedFiles: any) => {
  console.log(acceptedFiles);
}, []);
const { getRootProps, getInputProps } = useDropzone({ onDrop });

<FileUpload
  name="file"
  inputAttributes={{ ...(getInputProps() as FileUploadProps["inputAttributes"]) }}
  attributes={{ ...(getRootProps() as FileUploadProps["attributes"]) }}
>
  Drop files to attach
</FileUpload>
```

**Comment by blvdmitry** [comment]
It's ready now for the upcoming release. Thanks for sharing your ideas along the way 🙌

**Comment by blvdmitry** [comment]
Live in 2.6.0
