### ISSUE TITLE
[Feature Request] Wizard Component

### ISSUE THREAD

**Issue by X86-7** [formaat-design/reshaped#147]
Found another component that could definitely be useful.

Adding onto the form control, perhaps you could add a wizard component.

![image](https://user-images.githubusercontent.com/84218614/227823266-d2d36185-3b24-4273-83f7-1656c3e74256.png)

![image](https://user-images.githubusercontent.com/84218614/227823273-b2efb0c7-1626-4249-936e-746af4e79630.png)

I could easily use a modern form of this in my projects. Could really help with the onboarding process!

**Comment by bohdank1995** [comment]
Agree, this component is quite 'popular' and very useful to use from UX perspective. So I would like to have it Reshaped too!

**Comment by its-monotype** [comment]
The Wizard component is the same as the Steps component? If so, I really like that implementation https://saas-ui.dev/docs/components/navigation/stepper

**Comment by blvdmitry** [comment]
Yes, it is. I don't think it will ship with this name and I just keep the issue title, while most of the systems call it either Stepper or Navigation progress. In terms of design – I think it will be closer to the saas-ui but aligned with other Reshaped components. Planning to include it into the release coming after the next one

**Comment by blvdmitry** [comment]
Got the first version working, which is very basic atm. While I'm polishing the details, writing tests, docs, etc. – are there any specific features you would like it to have supported? I'll make sure to include those either in the component itself or as documentation examples

![Image](https://github.com/formaat-design/reshaped/assets/887379/7a244c9d-cb61-420b-a443-b9d14ea388aa)

**Comment by X86-7** [comment]
Oh beautiful! I think having subtitles, maybe the ability to have different variants? (Borders around the current one) Perhaps a vertical one in addition to horizontal?

**Comment by blvdmitry** [comment]
For the vertical one, would you expect it to be like in MUI with content that gets collapsed or the "mantine" approach where it's just the steps displayed vertically?

**Comment by X86-7** [comment]
I really like the collapsible approach. Keeps it nice and neat for smaller screens/busier sections.

**Comment by blvdmitry** [comment]
Not the final version yet, but I think it's getting close 🙂

https://github.com/formaat-design/reshaped/assets/887379/657bb3ba-e690-49a2-b56b-5873a70a1b55

**Comment by blvdmitry** [comment]
Finally done with both code and design, shipping in 2.5.0 on Monday :)
Thanks for following up on this 🙌
