### ISSUE TITLE
Automatic theme generation

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#151]
A theme generator that creates, based on `background-primary`, all related tokens

- background-primary-faded
- border-primary
- border-primary-faded
- foreground-primary
- background-primary-highlighted

like https://www.skeleton.dev/docs/generator

**Comment by blvdmitry** [comment]
Getting close to finally resolve this issue


![Image](https://github.com/formaat-design/reshaped/assets/887379/67b41486-e80b-4955-bf69-54fec0d335fc)

**Comment by blvdmitry** [comment]
It's ready in 2.5.0 now. Already on npm and deployed, announcing tomorrow. I assume there might be edge cases which can be improved further, so let me know
