### ISSUE TITLE
[Feature Request] Chip component

### ISSUE THREAD

**Issue by Madhavkabra** [formaat-design/reshaped#152]
A chip component is a good way to display selected filters. Current work around to do the same is the following code:

`
                    <MenuItem
                      size='small'
                      selected
                      roundedCorners
                      key={fieldKey}
                    >
                      <View direction='row' align='center' padding={[0, 3]}>
                        <Text variant='body-medium-2'>
                          {`${fieldKey} ${
                            filterTypeAndValue[`${fieldKey}`].type
                          } ${filterTypeAndValue[`${fieldKey}`].value}`}
                        </Text>
                        <Actionable
                          onClick={() => handleRemoveFilterFromChips(fieldKey)}
                        >
                          <Icon svg={<CloseIcon />} />
                        </Actionable>
                      </View>
                    </MenuItem>
`

![image](https://user-images.githubusercontent.com/36595067/236121434-8923e75b-4a40-4a43-a6ec-b4a570677f05.png)

**Comment by blvdmitry** [comment]
Hey, thanks for the request. We actually even have it on the feature list. Current assumption was that Badge could be a good option for rendering selected items but Chips indeed usually have other use cases

**Comment by blvdmitry** [comment]
It's coming in the next release as a part of Badge component, which now supports an additional large size, onDismiss/onClick and icons on both sides
![image](https://github.com/formaat-design/reshaped/assets/887379/d7691464-daec-4e63-843a-6f6c6d252a57)
