### ISSUE TITLE
[Bug] attributes added to <View.Item> are ignored

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#154]
![image](https://user-images.githubusercontent.com/87228994/236285463-cd9ff459-08c5-44ef-ab9f-7d119939f1f7.png)

![image](https://user-images.githubusercontent.com/87228994/236285441-ee01eb29-2131-44d8-9b08-cef90a49e17c.png)

**Comment by blvdmitry** [comment]
Fixed, coming in the next nightly
<img width="1257" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/a5cc1602-addc-42fe-9e65-29fdcb24a40d">
