### ISSUE TITLE
[BUG] Responsive Sheet Modal is broken

### ISSUE THREAD

**Issue by X86-7** [formaat-design/reshaped#155]
Any time the responsive sheet modal is called, it simply darkens the background and doesn't display the modal.

![image](https://user-images.githubusercontent.com/84218614/236841830-f4135abf-e338-4f00-a0e4-a4291da126ed.png)

It's also broken in the documentation on your website as well, so I know it's not just me.

**Comment by blvdmitry** [comment]
Fixed and shipped in nightly.1
