### ISSUE TITLE
[Bug] Skeleton component flickers when opacity changes

### ISSUE THREAD

**Issue by X86-7** [formaat-design/reshaped#157]
I noticed that when the skeleton component is used, it flickers between the changes in opacity.

https://i.gyazo.com/a8d54c6904742f4d2116271c9645960a.mp4

The video demonstrating it can be found above.

**Comment by blvdmitry** [comment]
Which browser / OS is this happening in for you? Can't reproduce it in my environment, the animation is there but I don't see the flickering

**Comment by X86-7** [comment]
I was using Windows 10 and Firefox. Don't see that flickering on MacOS. Will try again on my windows system and see if it does it still.

**Comment by blvdmitry** [comment]
Would also appreciate if you can try adding `transform: translateZ(0);` to the skeleton in the environment where it flickers and tell me if that improves the animation

**Comment by X86-7** [comment]
Sorry for not responding. I can't seem to replicate the issue on my side either so I'm going to assume it was something else unrelated to reshaped.
