### ISSUE TITLE
Remix: FOUC issue

### ISSUE THREAD

**Issue by muco-rolle** [formaat-design/reshaped#158]
I cloned the Remix starter and I'm experiencing
![Screenshot from 2023-05-10 03-19-22](https://github.com/formaat-design/reshaped/assets/43722815/a103136d-df6b-4ae2-bf97-ef89f0aefdba)
 a Flash Of Unstyled Content anyone has faced this issue?

**Comment by blvdmitry** [comment]
Hey, I'll check this today and will also try updating to the latest Remix since they've moved css support to stable

**Comment by blvdmitry** [comment]
I've checked the demo and it's indeed missing the SSR part. 
In Reshaped v1 it was `data-rs-theme="reshaped-light"` attribute on <body>
In Reshaped v2 nightly it is `data-rs-theme="reshaped" data-rs-color-mode="light"` attribute on <html>

**Comment by blvdmitry** [comment]
Updated the example: https://github.com/formaat-design/reshaped/blob/master/examples/starter-remix/app/root.tsx#L49
