### ISSUE TITLE
[Feature Request] Hover styles

### ISSUE THREAD

**Issue by mattlenz** [formaat-design/reshaped#160]
Is there currently a suggested approach to adding hover styles to components via props, without breaking into custom CSS?

**Comment by blvdmitry** [comment]
Hey, there is no standard way for doing that besides affecting some of the values based on the theme. Is there a specific case you're trying to solve?

**Comment by mattlenz** [comment]
Let's take this for example. The card on the right is the hover state.

<img width="659" alt="Screenshot 2023-06-15 at 7 34 16 am" src="https://github.com/formaat-design/reshaped/assets/208091/a18337e5-77fe-45ca-8b2d-b1eaa9836e72">

**Comment by blvdmitry** [comment]
For this or other similar use cases I would recommend one of the 2 following approached right now:
- Create a component with custom css which would use Reshaped tokens for styling and hover styles and compose multiple components together
- Take unstyled component like actionable and style it using our TailwindCSS integration

Both should work fine but depend on your tooling preference

**Comment by mattlenz** [comment]
Thanks @blvdmitry! We'll probably take the custom CSS approach :)
