### ISSUE TITLE
[Bug] Screen centers while editing text

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#161]
We're using a rich text editor and discovered that Reshaped is centering the screen to my cursor if I edit something in the rich text editor. This leads to an unexpected and harsh user experience. (Google Docs, Confluence, Notion etc. No one does this)

https://github.com/formaat-design/reshaped/assets/87228994/a697c02e-8d33-412d-8694-b68c6787ab67

**Comment by blvdmitry** [comment]
Hey, sorry for taking long on this one. Is it something you can reproduce on codesandbox now that Reshaped is available for use there?

**Comment by mmailaender** [comment]
Not more happening
