### ISSUE TITLE
[Feature] Add Reshaped to Figma's new Dev Mode

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#162]
I would love to see Reshaped as a Language option in Figma's new Dev Mode: 

![image](https://github.com/formaat-design/reshaped/assets/87228994/4a791d9f-5e3b-4fa5-83fe-2fc4f2fb2285)

**Comment by blvdmitry** [comment]
We'll wait for dev mode to get out of beta and see what features will be available natively. Going to create another issue once it happens.
