### ISSUE TITLE
Range Input

### ISSUE THREAD

**Issue by tonyfromundefined** [formaat-design/reshaped#164]
- A function to get a float between 0 and 1 is currently planned for our dashboard.
- I would like to receive that input as `type="range"`, but I wonder if there is a support plan in Reshaped.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by blvdmitry** [comment]
Hey, that's a good one. We'll prioritise this for the next release since it was already in our backlog

**Comment by blvdmitry** [comment]
Just merged this into the main branch and it's coming in the next release at the end of August, combining multiple new features for it. Sorry that you'll have to wait for it. 

<img width="416" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/de2736af-2bbe-4c77-be34-4ccf9b7b7f92">

**Comment by tonyfromundefined** [comment]
Thanks!
