### ISSUE TITLE
[Feature Request] Table Component

### ISSUE THREAD

**Issue by charles0122** [formaat-design/reshaped#166]
Maybe the positioning of reshaped is mobile or the homepage of the website, but in the background management system, the table is a very important component, and it is hoped to be increased, of course, it does not matter if it is not added.

**Comment by blvdmitry** [comment]
Hey, thanks for the request. We'll include the first iteration of the table for one of the upcoming releases. We won't be going for the advanced data grid features yet but might cover some of the typical functionality like composition support for the sorting / filtering. Are there any specific cases you want Table component to handle that would help your product?

**Comment by mmailaender** [comment]
I know that there are different types of tables, but for me, I would like to have a table that can be extended and filled by the user:

https://github.com/formaat-design/reshaped/assets/87228994/a07deb28-9718-4742-b8cb-887fd1582091

- Hovering between two lines/columns -> A plus icon appears to add a new line/column
- Selecting a line/column activates keyboard like backspace for deleting
- Selecting and holding a line/columns -> Reposition a line/column
- Selecting two cells -> Popover to merge/split cells

**Comment by blvdmitry** [comment]
So trying to balance the regular table requirements and the editing logic built on top, I think all the highlighted border and popovers should be build on top of the table on the product side. From Reshaped side, we'll be able to provide a compound component API that would give you access to each individual cell, calculate their sizes and dynamically change their rendering based on your state. Edit highlights should probably be positioned on top of the table based on the cell sizes and work with the product state

**Comment by blvdmitry** [comment]
First version is ready for the next release. Going to keep improving it afterwards based on the user feedback


![Image](https://github.com/formaat-design/reshaped/assets/887379/05e875c7-4fe6-44b5-b9a4-bfe906b26fa8)
