### ISSUE TITLE
Dropdown options get hidden randomly

### ISSUE THREAD

**Issue by Madhavkabra** [formaat-design/reshaped#167]
List of options in the Dropdown menu get hidden randomly, i.e they can not be seen but they can be interacted with, and the mouse still changes with the hover and clicking options works.

**Comment by blvdmitry** [comment]
Hey, can you provide a code snippet of the dropdown you have?

**Comment by Madhavkabra** [comment]
Here is the code snippet for the same

```
<DropdownMenu width="trigger">
                <DropdownMenu.Trigger>
                  {(attributes) => (
                    <Select
                      name={field.name}
                      inputAttributes={attributes}
                      placeholder={values[field.name]}
                      value={values[field.name]}
                    />
                  )}
                </DropdownMenu.Trigger>
                <DropdownMenu.Content>
                  {field.options.map(({ isAvailable, name, value }) => (
                    <DropdownMenu.Item
                      key={value}
                      onClick={() => onChangeValue(field.name, value)}
                    >
                      <Text color={!isAvailable ? 'disabled' : 'neutral'}>
                        {name}
                      </Text>
                    </DropdownMenu.Item>
                  ))}
                </DropdownMenu.Content>
              </DropdownMenu>```

**Comment by blvdmitry** [comment]
Trying to reproduce with the follow example and it seems to work as expected. I had to remove all external variables and function calls though so it might be happening because of the `onChangeValue` logic. Also what looks strange to me is that you're changing the text color to disabled but you're not adding `disabled` flag to the DropdownMenu.Item

```
import { Reshaped, DropdownMenu, Select, Text, View } from "reshaped";
import "reshaped/themes/reshaped/theme.css";

export default function App() {
  return (
    <Reshaped theme="reshaped">
      <View padding={4}>
        <DropdownMenu width="trigger">
          <DropdownMenu.Trigger>
            {(attributes) => (
              <Select
                name="hey"
                inputAttributes={attributes}
                placeholder="Hey"
                value="Hey"
              />
            )}
          </DropdownMenu.Trigger>
          <DropdownMenu.Content>
            {[
              { name: "1", value: "1", isAvailable: true },
              { name: "2", value: "2" }
            ].map(({ isAvailable, name, value }) => (
              <DropdownMenu.Item key={value}>
                <Text color={!isAvailable ? "disabled" : "neutral"}>
                  {name}
                </Text>
              </DropdownMenu.Item>
            ))}
          </DropdownMenu.Content>
        </DropdownMenu>
      </View>
    </Reshaped>
  );
}

```

**Comment by blvdmitry** [comment]
Closing this for now since it's getting stale, let me know if you can reproduce this again

**Comment by ForrestCogna** [comment]
@blvdmitry I have also run into this issue but it has been difficult to isolate. However, some additional clues:
- Occurs when clicking an item to close the content menu **only when dropdownmenu.trigger is in bottom 50% of container**
- a scaled-down, opacity: 0 version of the dropdown menu is added to the dom and blocks events in elements behind the hidden dropdownmenu content popover

**Comment by blvdmitry** [comment]
Let me try to investigate it again. If you have any code snippet you can share - that would help a lot

**Comment by larsmennen** [comment]
@blvdmitry I don't have an isolated example to reproduce unfortunately, but I think it's related to the `transitionend` event not firing on the `content` div, which then leaves it in a hidden state. 
If I manually force a transform transition by adding it from the Dev Tools it correctly removes the hidden div. I'm not sure why that event isn't being fired.

I only seem to be able to run into the issue if the triggering button is very close to the bottom of my viewport.

We found a workaround now by setting `disableHideAnimation={true}` on `DropdownMenu`. I think that option is undocumented (or at least I couldn't find it), so that may be worth adding to the docs?

**Comment by blvdmitry** [comment]
Looking at this again, @larsmennen @Madhavkabra do you maybe have a video demo of how this issue looks visually?

**Comment by blvdmitry** [comment]
Goin to close this for now due to inactivity and not being able to reproduce it, let's reopen it again if it's still an issue

**Comment by vladoyoung** [comment]
Almost thought that this was happening to me too, until I realised I was using `DropdownMenu.Content` twice:


```
<DropdownMenu>
	<DropdownMenu.Trigger>
		{(attributes) => <Button attributes={attributes} icon={IconMoreHoriz} variant="faded" color="primary" />}
	</DropdownMenu.Trigger>
	<DropdownMenu.Content>
		<DropdownMenu.Item onClick={addUsersDropdownOnClick}>Add user</DropdownMenu.Item>
	</DropdownMenu.Content>
	<DropdownMenu.Content>
		<DropdownMenu.Item onClick={copyUsersDropdownOnClick}>Copy users</DropdownMenu.Item>
	</DropdownMenu.Content>
</DropdownMenu>
```

So keep this in mind for debugging if it happens to you.
