### ISSUE TITLE
Dropdown menu is not relative to parent

### ISSUE THREAD

**Issue by Madhavkabra** [formaat-design/reshaped#169]
Menu for Dropdown component has position set relative to viewport and not parent element. This causes problems when the dropdown is in a scrollable component which is scrolled while the dropdown is open.

![image](https://github.com/formaat-design/reshaped/assets/36595067/81cf37dc-e834-4796-85aa-119deeba2574)

**Comment by blvdmitry** [comment]
👍 going to add this to 2.3 backlog, thanks for the request

**Comment by mmailaender** [comment]
This is also happening for Autocomplete component https://reshaped.so/content/docs/components/autocomplete

**Comment by blvdmitry** [comment]
Makes sense, all dropdowns are the same component under the hood, so the fix will patch all these behaviours

**Comment by blvdmitry** [comment]
Got it working in the next release branch. I will take a look into a few more reported issues and will ship a patch with the fixed somewhere during the week

<img width="448" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/1ab8e88b-38db-46ba-abed-1407feac0be0">

**Comment by blvdmitry** [comment]
@Madhavkabra one thing I forgot to ask. It's now rendered relative to the trigger when used inside a scrollable area, but that also means it will get cut by the overflow. Do you have a use case where it has to still be rendered outside the scrollable area but still follow the trigger on scroll?
