### ISSUE TITLE
Update the shapes of certain icons that have defects

### ISSUE THREAD

**Issue by antongridz** [formaat-design/reshaped#171]
Hello! I have come across some issues with the icons in the Reshaped pack.

The list of broken icons:
- battery-charging
- camera-off
- dribbble
- maximize
- minimize
- table
- watch
- wind

In addition, the message-circle icon shape needs to be outlined. Updating from the latest version of the Untitled UI icon pack would be great.

Thanks!

**Comment by blvdmitry** [comment]
Updated the assets, should be out with the next release
