### ISSUE TITLE
Active tab is not centered 

### ISSUE THREAD

**Issue by Madhavkabra** [formaat-design/reshaped#173]
When we have scrollable tabs, some tabs can be only partially visible. If such a tab is clicked, the scroll should adjust and center the active tab such that it is at-least completely visible to the user.

![Screenshot_20230904-151534](https://github.com/formaat-design/reshaped/assets/36595067/9bf0b96c-0692-449e-8f88-96196f8863ac)

In the image, we have selected a tab that is partially out of the screen and is active, but the scroll does not update to center it.

**Comment by blvdmitry** [comment]
Going to add to one of the upcoming release, meanwhile you should be able to scroll the container in the onChange handler

**Comment by blvdmitry** [comment]
Done, coming in the next release

https://github.com/formaat-design/reshaped/assets/887379/217c7fd5-9e97-4207-8ea8-e5cd79c9ec9c
