### ISSUE TITLE
Input fields accessibility in small screens (mobile)

### ISSUE THREAD

**Issue by Madhavkabra** [formaat-design/reshaped#174]
In a mobile screen, when users click on input text fields, the screen should scroll and adjust to ensure the text field is in view for accessibility. This happens in chrome browsers but does not happen in firefox browser. 

This might be a browser issue, or it can be an implementation problem, please look into it, so that the application behavior can be standard across browsers.

**Comment by blvdmitry** [comment]
Going to definitely check again. In general we're not using anything custom there, so most likely it's the default browser behaviour but I'll let you know later

**Comment by blvdmitry** [comment]
Hey, @Madhavkabra, can you provide more details about the environment? Browser version (if available), OS, etc.?
I've just tried on iOS firefox and it's working as expected

**Comment by mmailaender** [comment]
Somehow it's now working - @Madhavkabra we can close this issues 🙂
