### ISSUE TITLE
Toast does not hide if hide is called too soon

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#175]
We have the following code to show and hide a Toast

```
const loadingId = toast.show({
      title: '...',
      text: '...',
      color: 'neutral',
      icon: <Loader color="primary" />,
      timeout: 0,
    })
    await dispatch(
      update(something)
    )
    toast.hide(loadingId)
```

However if the promise rejects immediately then it seems that the `hide.toast` is missed as the Toast remains

If we add a `setTimeout` then the toast is hidden, pressumably because following this the Toast has completed being shown so is ready to be hidden:

```
const loadingId = toast.show({
      title: '...',
      text: '...',
      color: 'neutral',
      icon: <Loader color="primary" />,
      timeout: 0,
    })
    await dispatch(
      update(something)
    )
    setTimeout(() => toast.hide(loadingId), 3000)
```

**Comment by blvdmitry** [comment]
Hey, thanks for reporting this, I'll add this to the backlog for the upcoming release

**Comment by blvdmitry** [comment]
Fixed, coming in the next release
