### ISSUE TITLE
TextField component throws error on autofill

### ISSUE THREAD

**Issue by rauloaida** [formaat-design/reshaped#177]
Summary: when using the reshaped.so TextField component in a Next.js project, an error is thrown every time the users selects an autofill value pre-stored in their browser. Happens across both Chrome & Safari. Issue is persistent from Reshaped v2.0.3 to v2.3.2.

Steps to replicate:
1. Open your IDE of choice.
2. Clone my [example repo](https://github.com/rauloaida/autofill-bug.git) OR you can use the app I [deployed to vercel.](https://autofill-bug.vercel.app/)
3. Run `npm install` && `npm run dev`.
4. In your browser, open the localhost url & port.
5. Open your browsers debug console. 
6. Click on TextField component to focus and select an autofill value. If no autofill value is present, I found [Safari allows](https://support.apple.com/guide/safari/autofill-ibrwa005/mac#:~:text=In%20the%20Safari%20app%20on,%3E%20Settings%2C%20then%20click%20AutoFill.&text=Complete%20forms%20with%20information%20from%20any%20contact%20card%20in%20Contacts.) you to generate a random autofill email address to use. 
7. Observe error. See attached screenshots/recording for reference.

Versions:
- reshaped v2.0.3 and 2.3.2
- Chrome v117.0.5938.92 
- Safari 16.5.1

<img width="704" alt="Screenshot 2023-09-21 at 2 16 36 PM" src="https://github.com/formaat-design/reshaped/assets/16652371/015f86fe-5c16-4f3f-9278-c65d4068bd26">
<img width="639" alt="Screenshot 2023-09-21 at 2 15 35 PM" src="https://github.com/formaat-design/reshaped/assets/16652371/443ee889-6705-4dd4-8e50-2fd6223c1fd0">

**Comment by blvdmitry** [comment]
Hey, this error looks like something that can be happening if your application is not wrapped with Reshaped provider, can you check if that's the case?

**Comment by JeromeDane** [comment]
Yep, it's wrapped. Here's the implementation in the minim [reproducible example](https://github.com/rauloaida/autofill-bug): https://github.com/rauloaida/autofill-bug/blob/main/src/app/page.tsx

<img width="1448" alt="image" src="https://github.com/formaat-design/reshaped/assets/451066/4a80f68e-2807-4631-97e7-0546f9d7ad07">

**Comment by rauloaida** [comment]
<img width="1876" alt="Screenshot 2023-09-25 at 10 01 59 AM" src="https://github.com/formaat-design/reshaped/assets/16652371/dd37203e-c508-4d2a-9abd-8279e940fc00">
Seems to do it for me in the sandbox too. I opened a incognito tab just in case. It also happens on other machines/users that tried this on my team.

**Comment by blvdmitry** [comment]
Got you. Can't reproduce this yet but I think this means that in some cases `handleKeyUp` can get triggered without the correct event. I'll release a patch for this later today and going to let you know so you can confirm it works, thanks for the heads up!

**Comment by blvdmitry** [comment]
Turns out browsers trigger keydown/keyup events when you're clicking on the autocomplete with your mouse. In that case `event.key` is undefined. I've added additional checks to prevent the errors from happening in that case. Going to release a patch with the fix and share here once it's live. Looking at one more issue reported to resolve them together

**Comment by blvdmitry** [comment]
Released 2.4.2 with the changes, can you check if it works as expected for you now?

**Comment by rauloaida** [comment]
This fixed it! amazing, thank you!
