### ISSUE TITLE
Figma variant/component for ghost button using Button.Aligner

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#179]
**Is your feature request related to a problem? Please describe.**
In figma the ghost button always looks misaligned to the text. In the code we have the Button.Aligner solution, but not in figma

**Describe the solution you'd like**
Button.Aligner functionality added to figma

**Describe alternatives you've considered**
I could manually edit the padding on the button, but it would be good to have it on the design system level

**Comment by blvdmitry** [comment]
I'm struggling to find a proper way to support this even with some creative workarounds in Figma. The other option is like you've mentioned to just provide a variant with the padding removed but it would break the highlighted state of the button (and all non-ghost variants if applied as a separate property). 

I'll keep looking today but it might be that the best option is to just remove the padding on the button instance until Figma implements negative auto layout values (which they already did for gap)

**Comment by blvdmitry** [comment]
We'll look into it in the prep for 3.0 as we've discovered it should be possible to assign negative auto layout values using variables: https://github.com/orgs/formaat-design/projects/2/views/1?pane=issue&itemId=58597261. Closing this issue as a duplicate
