### ISSUE TITLE
Missing figma variant for active text field

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#181]
Non active state
<img width="364" alt="Screenshot 2023-10-06 at 11 49 49" src="https://github.com/formaat-design/reshaped/assets/56936483/d977451a-8fe6-4fec-a04f-94f7ece35d16">
Active state
<img width="361" alt="Screenshot 2023-10-06 at 11 50 00" src="https://github.com/formaat-design/reshaped/assets/56936483/af3f7e2b-73ab-465d-b7c4-43a47b4ed45c">

I can't see a figma variant for the active state of a text field in the figma components? The only options under status are default, error and disabled

**Comment by blvdmitry** [comment]
Coming in the next release
<img width="944" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/bcb91bd0-e85d-43bf-ae32-7a42b1bed53e">
