### ISSUE TITLE
Tooltip on on non-button components?

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#182]
I would like to put a tooltip on a Skeleton, but I don't think this is possible? Is this correct?

**Comment by blvdmitry** [comment]
Hey, in order to keep it accessible, tooltips should have a focusable element linked to it. That way it will be accessible for keyboard users. What you can do is wrap a Skeleton with Actionable or with a `tabIndex={0}` div and pass Tooltip attributes in the render function to that element

**Comment by b-graves** [comment]
Apologies for the slow response. This makes a lot of sense thank you, I'm using the Actionable solution, thanks!
