### ISSUE TITLE
Autofill popover offset in reshaped 2.4.4

### ISSUE THREAD

**Issue by rauloaida** [formaat-design/reshaped#183]
**Describe the bug**
The position of the autofill popover is offset when compared with input field. Horizontal position of autofill depends on window width. Bug not present in 2.4.2, introduced in 2.4.4 to the best of my digging. 

**Expected behavior**
Autofill popover is centered on the input field being clicked. 

**Screenshots**
<img width="1644" alt="2 4 4 - min reproducible error" src="https://github.com/formaat-design/reshaped/assets/16652371/41e29e05-af8d-4201-99b0-c9faf8db9a00">

<img width="1112" alt="safari" src="https://github.com/formaat-design/reshaped/assets/16652371/34adb550-233c-4c27-ad2b-9980a338023f">

**To Reproduce**
Open your IDE of choice.
Clone my [example repo](https://github.com/rauloaida/autofill-bug.git) OR go to the [vercel app](https://autofill-wn5i85dha-vincent-experiments.vercel.app/) I deployed.
Go to branch [autofill-popover-off-center-bug](https://github.com/rauloaida/autofill-bug/tree/autofill-popover-off-center-bug)
Run npm install && npm run dev.
In your browser, open the localhost url & port.
Click on TextField component to focus and select an autofill value. If no autofill value is present, I found [Safari allows](https://support.apple.com/guide/safari/autofill-ibrwa005/mac#:~:text=In%20the%20Safari%20app%20on,%3E%20Settings%2C%20then%20click%20AutoFill.&text=Complete%20forms%20with%20information%20from%20any%20contact%20card%20in%20Contacts.) you to generate a random autofill email address to use.
Observe error. See attached screenshots/recording for reference.
Versions:

Reshaped 2.4.4
Chrome v117.0.5938.92
Safari 16.5.1

**Comment by blvdmitry** [comment]
Thanks, I can reproduce this and know why it happens now:  
We're adding negative margins for the input to keep it clickable when slots are used, which then affects the position of the native autocomplete

Going to find a way around it and ship a patch

**Comment by blvdmitry** [comment]
I've published 2.4.5 with the fix in case this is blocking, but it also includes minor updates for the default theme values related to the next minor release. You can either just update to 2.4.5 and try if the fix is working or if keeping current theme values is important - you can keep them as a custom theme. They will be updated for the Figma library in 2.5.0 as well.

**Comment by rauloaida** [comment]
Thanks for the update, just switched for 2.4.4 to 2.4.5 in my code example. Still looks a little wonky, see attached screenshots. My guess it that the autofill popover is justify: center instead of justify: start. 
<img width="1688" alt="expected" src="https://github.com/formaat-design/reshaped/assets/16652371/ccc509b1-d423-4c90-b09f-4f8d06d04c4e">
<img width="1597" alt="actual" src="https://github.com/formaat-design/reshaped/assets/16652371/be619e50-877c-49bd-976e-d6368e4a1399">

**Comment by blvdmitry** [comment]
And this is a native autocomplete, right? Does it behave correctly in the case of replacing TextField with a native html input?

**Comment by rauloaida** [comment]
You are correct! I guess this is the default behavior, so should be good to go. See attached screenshot of native html only. 
<img width="318" alt="htmlonly" src="https://github.com/formaat-design/reshaped/assets/16652371/e3a69d74-86f6-4eb7-96ba-b1eb17ea80b4">

Is there any indication when 2.5.0 will be coming out? checked the roadmap page but I don't see any date pinned to it. Thanks!

**Comment by blvdmitry** [comment]
One task left for the release there, so planning to be done with it around this Wed/Thu.
Thanks for checking the native implementation out!

**Comment by rauloaida** [comment]
@blvdmitry getting this in my implementation. Was reshaped/cli/theming/definitions/base removed in 2.4.4 > 2.4.5 ?

<img width="849" alt="Screenshot 2023-10-18 at 10 46 34 AM" src="https://github.com/formaat-design/reshaped/assets/16652371/be239fec-b379-4817-9dc8-b6f3020c960e">

**Comment by blvdmitry** [comment]
Hey, this was a file private to the package (no real way to mark that way unfortunately). But you can also import this definition from `reshaped/themes` now. It will be added to the docs in 2.5.0

**Comment by rauloaida** [comment]
Upgraded to Reshaped 2.5.0 today and changed the import from

`import baseDefinitions from 'reshaped/cli/theming/definitions/base'` 
to:
`import baseDefinitions from 'reshaped/themes'`

Now getting the error below, I've rebuilt the theme just in case. 
<img width="593" alt="Screenshot 2023-10-30 at 6 20 20 PM" src="https://github.com/formaat-design/reshaped/assets/16652371/6bfed2bd-1ee7-45c7-96f9-75537e4a7198">

The code snippet where this is used:
```
'@media': {
			[`screen and (min-width: ${baseDefinitions.viewport.l.minPx}px)`]: {
				position: 'static',
				transition: 'unset',
				width: 'unset',
				translate: 'unset',
				zIndex: 'unset'
			}
		}
```

Not sure if the docs have updated or if you have any suggestions, currently not building on 2.4.4 and above ;(

**Comment by blvdmitry** [comment]
Let me check this, I think viewports might be stored in a separate object that was not a part of the js theme definition, so I'll make sure to include it and release a patch with it

**Comment by rauloaida** [comment]
Let me know when you have an update! or if there is anything else that I can provide from my end

**Comment by blvdmitry** [comment]
Just checking it again and it actually seems to exist there: https://codesandbox.io/s/objective-colden-p894rr?file=/src/App.tsx

The types are not great though so I'm going to make sure they work as expected in a patch. Does output 900 in your case as well?

**Comment by blvdmitry** [comment]
Updated the theme definition types in 2.5.5

**Comment by rauloaida** [comment]
Unless I'm missing something it looks like 'base' is not being exported correctly, it errors in your codesandbox if you give it a few seconds to run the typescript checks. I get the same error when trying to use 2.5.5 in my own repo. See attached.

<img width="614" alt="Screenshot 2023-11-01 at 5 16 14 AM" src="https://github.com/formaat-design/reshaped/assets/16652371/c54ff9f3-f93a-42bb-b2d8-ce839084d6ec">

**Comment by blvdmitry** [comment]
It's `baseThemeDefinition`

**Comment by rauloaida** [comment]
Works, thank you!
