### ISSUE TITLE
Badge overflows input in Autocomplete - Composition docs

### ISSUE THREAD

**Issue by its-monotype** [formaat-design/reshaped#188]
**Describe the bug**
In the [autocomplete composition docs](https://reshaped.so/content/docs/components/autocomplete#composition), the badge overlaps autocomplete input with the placeholder making placeholder cut almost by half depending on badge size.

**Expected behavior**
Input/Placeholder should be visible

**Screenshots**
![image](https://github.com/formaat-design/reshaped/assets/79363260/f01a76b5-0420-4403-9a24-4acce98fe3eb)

**Comment by blvdmitry** [comment]
Thanks, fixed it locally, going to release a patch today
<img width="290" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/722ef87c-5bcc-4bbd-aa39-b05c3dca6e85">
