### ISSUE TITLE
Dropdown content should remain fixed when scrolling from GNB

### ISSUE THREAD

**Issue by irrationnelle** [formaat-design/reshaped#192]
**Describe the bug**

Hello! First, I'd like to thank you for creating such a wonderful library; it's been incredibly useful. 

However, I have one issue I'd like to address. When I declare a Dropdown Trigger on the GNB and click it to display the Dropdown Content, the content moves with the scroll. 

The Dropdown Content should remain fixed to the GNB's Dropdown Trigger regardless of scrolling.

**To Reproduce**

- 1. Make a GNB with `position: fixed`
- 2. Add a component as Dropdown Trigger into GNB
- 2. Make a content pages with `padding-top: var(--header-height)`
- 3. `overflow-y: auto` or default setting for `<body>` tag
- 4. And then, click the Dropdown Trigger and scroll down. We could see Dropdown Content moves with scroll.

**Expected behavior**

The Dropdown Content remains fixed when scrolling.

**Environment (please complete the following information):**

 - OS: MacOS Sonoma
 - Browser: Chrome 118.0.5993.117 (arm64)
 - Version: reshaped 2.5.3

**Screenshots**

https://github.com/formaat-design/reshaped/assets/10165823/202861a0-db95-487e-b699-6c7274736c1c

**Comment by blvdmitry** [comment]
Thanks for reporting, we've recently fixed it for scrollable areas but haven't got to managing it for the fixed eleemnts. Going to include it for the next release

**Comment by blvdmitry** [comment]
Got it working, shouldn't require changing anything in the code on your side. 
Going to release a patch in a moment

https://github.com/formaat-design/reshaped/assets/887379/11416aa9-ce58-46c6-95ce-127c35d7bb76

**Comment by blvdmitry** [comment]
It's live now in 2.5.6

**Comment by irrationnelle** [comment]
It works great, thanks for the quick fix!
