### ISSUE TITLE
TextField long prefix overflow

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#195]
I did a design for a TextField with a prefix of "Estimated value" in figma to look like this:

![image](https://github.com/formaat-design/reshaped/assets/56936483/9e9d09b7-1d4b-4984-9e5c-459b459cba44)

However when I have come to implement it I have written the following code:

```
<TextField.Aligner>
  <TextField
    name="estimated-value"
    variant="headless"
    placeholder="No value"
    prefix="Estimated value"
    startSlot={<Icon svg={<IconBarChart2 />} />}
  />
</TextField.Aligner>
```

However it looks like this:

![Screenshot 2023-11-08 at 16 52 20](https://github.com/formaat-design/reshaped/assets/56936483/5796bd73-b52a-4fdb-ac4c-050668a0b40e)

I'm assuming there is some kind of issue with the prefix being too long? I tried without aligner, without icon and other variants but all the same

Thanks!

**Comment by blvdmitry** [comment]
Hey, can you check if this is still happening on the latest patch? (2.5.9)
I've just checked that the issue was there in 2.5.0 but when I tried 2.5.9 it was gone without any changes to the code:

https://codesandbox.io/s/dreamy-knuth-y5h3jn?file=/src/App.tsx

**Comment by b-graves** [comment]
ah apologies, yes all good with the latest patch, thank you!
