### ISSUE TITLE
Button font color is not set to black when the button color is set to a light color

### ISSUE THREAD

**Issue by jkbreunig** [formaat-design/reshaped#199]
**Describe the bug**
The button font color is not set to black when the button color is set to a light color.  The button font color should be set to black if a black font color has a higher contract ratio than a white font color for the set button color.

**To Reproduce**
Set primary color to a color that does not contrast enough with white such as #8957b6 or #FFFF00
```
<Button
            variant="solid"
            color="primary"
            size="large"
            rounded
            fullWidth
            onClick={onClick}>
            Title
        </Button>
```

**Expected behavior**
The button font color should be set to black if black font color contrasts more with the button color than white font color.

**Screenshots**
Actual
![Screenshot 2023-11-21 at 3 26 26 PM](https://github.com/formaat-design/reshaped/assets/1190977/93da625f-9bc2-4270-a269-209478e4a78f)
![Screenshot 2023-11-21 at 3 17 32 PM](https://github.com/formaat-design/reshaped/assets/1190977/5c11e707-74b7-4b7a-8ba3-c6f58131b4cd)

Expected
![Screenshot 2023-11-21 at 3 26 11 PM](https://github.com/formaat-design/reshaped/assets/1190977/21cdd2a4-11ae-4820-8dd8-f18caaf2fded)
![Screenshot 2023-11-21 at 3 24 31 PM](https://github.com/formaat-design/reshaped/assets/1190977/22d0411e-e3e9-4d4b-be77-661eb6053c0e)

**Environment (please complete the following information):**
 - Version 2.5.9

**Additional context**

**Comment by blvdmitry** [comment]
Hey, can you try reproducing it here or send your reshaped.config.js file contents? 
I've tried reproducing this using the colors you've suggested but it still seems to work as expected

https://codesandbox.io/p/sandbox/practical-antonelli-8lvwlw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp8xeioi00073b6haq9f3xsf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp8xeioi00033b6hzrlp5k24%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp8xeioi00043b6hugjn4e7b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8xeioi00063b6h2va5ld87%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp8xeioi00033b6hzrlp5k24%2522%253A%257B%2522id%2522%253A%2522clp8xeioi00033b6hzrlp5k24%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clp8xeioi00063b6h2va5ld87%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8xeioi00053b6hi4rstf34%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clp8xeioi00063b6h2va5ld87%2522%252C%2522activeTabId%2522%253A%2522clp8xeioi00053b6hi4rstf34%2522%257D%252C%2522clp8xeioi00043b6hugjn4e7b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clp8xeioi00043b6hugjn4e7b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by jkbreunig** [comment]
hey, sorry I provided the incorrect hex value for the teal color (#00E5C4). 

Expect primary color "#00E5C4" to have black font color since it has a higher contrast ratio than white font color
https://codesandbox.io/p/sandbox/adoring-gates-c4txgj?file=%2Fsrc%2FApp.tsx%3A17%2C4

I've resolved the issue that caused the white font color for yellow primary color.

**Comment by blvdmitry** [comment]
Updated the on colors generation in 2.6.2, it should be more precise now but it also means it might have changed for other colors as well. This should be a good change but just making sure you're aware in case you were relying on a color that didn't have enought contrast according to WCAG
