### ISSUE TITLE
add ios sheet behavior to bottom sheet modal

### ISSUE THREAD

**Issue by jackiehluo** [formaat-design/reshaped#201]
**Is your feature request related to a problem? Please describe.**
the bottom sheet modal looks like the ios sheet but doesn't have the same interaction pattern (rubber band effect and swipe to close).

**Describe the solution you'd like**
add support for touch interactions on mobile to pull down on the bottom sheet modal to close it (i.e., https://developer.apple.com/design/human-interface-guidelines/sheets#iOS-iPadOS). could be achieved with framer motion or similar (example: https://github.com/Temzasse/react-modal-sheet).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by blvdmitry** [comment]
Releasing it in the next minor

https://github.com/formaat-design/reshaped/assets/887379/4ea7a330-63d3-454a-b32a-0885160ffe40
