### ISSUE TITLE
Initial page load flickers when using NextJS 14 in SSR scenario

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#206]
**Describe the bug**
Initial page load flickers when using NextJS 14 in Server Side Rendering

**Screenshots**
<video src="https://github.com/formaat-design/reshaped/assets/81009071/2e526cb6-e836-4dc7-b721-2697b4bf9196"></video>

**Environment:**
 - Respahed (v2.7.1)
 - NextJS (v14.0.3)
 - React (v18.2.0)

**Comment by blvdmitry** [comment]
Hey there, can you make sure you have data-rs-theme attribute on your html element? That way all variables will be available even during the SSR 

https://reshaped.so/docs/getting-started/react/installation#server-side-rendering

**Comment by hahahumble** [comment]
Thank you for your response, this solved my issue.
