### ISSUE TITLE
Viewport(Hidden) Not Working in Version 2.8.3

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#210]
**Describe the bug**
The viewport is not functioning in version 2.8.3. When I reverted back to version 2.7.1, it started working normally again.

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/sandbox/dreamy-bush-33ml6t?file=%2Fsrc%2FApp.tsx%3A16%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr8z8tus00063b6ifkrwzhnl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr8z8tus00023b6izdzo8lm4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr8z8tus00033b6io0gxoldk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr8z8tus00053b6ihb92h7k4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.14360027315767%252C47.85639972684233%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr8z8tus00023b6izdzo8lm4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8z8tur00013b6i54hij0b9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr8zd33r00023b6hpa4b4rho%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr8z8tus00023b6izdzo8lm4%2522%252C%2522activeTabId%2522%253A%2522clr8zd33r00023b6hpa4b4rho%2522%257D%252C%2522clr8z8tus00053b6ihb92h7k4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8z8tus00043b6ihjl854od%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr8z8tus00053b6ihb92h7k4%2522%252C%2522activeTabId%2522%253A%2522clr8z8tus00043b6ihjl854od%2522%257D%252C%2522clr8z8tus00033b6io0gxoldk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr8z8tus00033b6io0gxoldk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10%257D)

**Environment:**
- NextJS (v14.0.3) 
- React (v18.2.0)

**Comment by blvdmitry** [comment]
Does this happen to you only on codesandbox or in other environments as well? I think it might be related to the viewport theming, where I've stopped precompiling media queries before publishing the package (since they can change based on the product theme). It should still work as expected if you have `postcss.config.js` file with the Reshaped postcss config. 

Can you check if your project has it included?
https://reshaped.so/docs/getting-started/integrations/next#add-a-postcss-config

**Comment by hahahumble** [comment]
This situation only occurs in CodeSandbox. 

It also happened in my local project before, but was resolved after I imported the generated `media.css`.

**Comment by blvdmitry** [comment]
I guess I should update the default template to use Vite or Webpack directly on codesandbox to make sure this works out of the box. Curious why it doesn't work for you out of the box and you had to manually import a media file though, it should get imported automatically. Is your setup available publicly or otherwise can you also check if there are any difference compared to https://github.com/formaat-design/reshaped/tree/main/examples/starter-next?

**Comment by hahahumble** [comment]
I've figured out the reason. I didn't use the destructuring assignment syntax in the postcss configuration file, which is why I needed to manually import `media.css`.

```js
const config = require('reshaped/config/postcss');
```

**Comment by blvdmitry** [comment]
Ah, makes sense, thanks for sharing. I'll see if I can highlight that in the docs better
