### ISSUE TITLE
Placeholder Color Used in TextField and Autocomplete is Different from TextArea

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#211]
**Describe the bug**
The Placeholder Color Used in TextField and Autocomplete is Different from TextArea.

**Additional context**
<img width="300" src="https://github.com/formaat-design/reshaped/assets/81009071/267ce5bf-5074-4cb1-8466-12218b0b0054"/>

**Comment by blvdmitry** [comment]
<img width="219" alt="image" src="https://github.com/formaat-design/reshaped/assets/887379/1b60d614-7993-4b48-9918-a59209353663">

Fixed in 2.8.4, thanks for opening up a ticket for this!
