### ISSUE TITLE
Assigning the attributes of a <Tooltip> to a <View> components within throws a TS error

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#213]
**Describe the bug**
Assigning the attributes of a <Tooltip> to a <View> components within throws the following TS error:
TS2322: Type TriggerAttributes is not assignable to type Attributes<"div", void>

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://codesandbox.io/p/sandbox/distracted-david-smh2mr

**Expected behavior**
There should be no TS error.

**Screenshots**
<img width="955" alt="image" src="https://github.com/formaat-design/reshaped/assets/9999658/3db95f71-f94c-48d4-8166-c6d3397b2bab">
<img width="976" alt="image" src="https://github.com/formaat-design/reshaped/assets/9999658/751eea23-4a2f-4701-b6ae-3e0eee075b77">

**Environment (please complete the following information):**
 - OS: macOS - 14.2.1 (23C71)
 - Browser: Chrome
 - Version: 120.0.6099.216 (Official Build) (arm64)
 - IDE: WebStorm 2023.3.2 Build #WS-233.13135.92, built on December 19, 2023

**Additional context**
For this specific project configuration, putting in the following comments before the line with the error is the temporary solution:
`// eslint-disable-next-line @typescript-eslint/ban-ts-comment`
`// @ts-ignore`

**Comment by blvdmitry** [comment]
Hey, thanks for reporting this. This is an expected behavior since Tooltips rely on the focus event as well for the keyboard navigation and View is rendered as a `div` which won't receive focus. What you can do is wrap it with `Actionable` utility and pass the attributes to it instead of passing them to View

**Comment by vladoyoung** [comment]
Ah, I wasn't aware of that, sorry!

I also tried adding the `as` attribute like so: `<View as="button"...>`. That works too, but created the default browser buttons style, so that's not ideal either:
![image](https://github.com/formaat-design/reshaped/assets/9999658/5c61129e-69ba-4664-b3c8-0f0786e7d382)

I'll stick with your solution. Thanks for the quick reply!

You can close the issue if you think there's nothing to add.
