### ISSUE TITLE
Custom icon slot for buttons in figma

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#214]
It is possible to add custom icons to buttons in the code by passing a custom icon as a prop to a button, but it's not possible to do this in figma without detaching from the component. Could we have an option to have a slot instead of an icon? Thanks!

**Comment by blvdmitry** [comment]
Hey, right now you can try adding your custom icons to the icon component in the library but we have indeed discussed using icons through swapping instances of components. We'll plan the migration for this approach soon

**Comment by b-graves** [comment]
Ah I see thank you, I will try that
