### ISSUE TITLE
Slider component causes parent to overflow 

### ISSUE THREAD

**Issue by rauloaida** [formaat-design/reshaped#216]
**Describe the bug**
- the reshaped Slider component causes the parent to overflow when dragged to the max value (right side).
- this adds a horizontal scroll bar to the page.
- since we can't control the parent component, we cannot use *overflow-x: hidden* to fix the issue.

**To Reproduce**
[Code Sandbox Demo ](https://codesandbox.io/p/sandbox/slider-demo-tdq4dj?file=%2Fsrc%2FApp.js%3A8%2C56)

**Expected behavior**
- the value label does/slider does not cause the parent component to overflow.

**Environment (please complete the following information):**
- Reshaped 2.9.2
- Chrome v117.0.5938.92
- Safari 16.5.1

**Additional context**
- we are using the Reshaped slider component inside an iframe embed, which is causing the 3rd party parent page to overflow.

**Comment by blvdmitry** [comment]
Published an update in 2.9.3, let me know if that works for you 🙌

https://github.com/formaat-design/reshaped/assets/887379/66196450-d3c9-4039-a006-30afc68dde6e

**Comment by rauloaida** [comment]
incredible, thank you so much this is perfect!
