### ISSUE TITLE
Remix Vite Setup Issues

### ISSUE THREAD

**Issue by muco-rolle** [formaat-design/reshaped#224]
**Describe the bug**
I installed Reshaped in a new Remix Vite app, following the integration guide that is featured on the website. If you run the server you encounter with an `Unexpected token 'export'` message on the screen.

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://stackblitz.com/edit/remix-run-remix-2cgh4v?file=postcss.config.js,app%2Froot.tsx,app%2Froutes%2F_index.tsx

**Expected behavior**

**Screenshots**
![Screenshot from 2024-03-07 10-45-37](https://github.com/formaat-design/reshaped/assets/43722815/ada60ca2-025d-4a7b-ae6d-48baa06513fa)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 2.10.1

**Comment by blvdmitry** [comment]
Hey, seems like the docs were missing one step which we actually have in the example in the repo.  You need to add `
  serverDependenciesToBundle: ["reshaped"]` to your `remix.config.js`. Just tried it with the latest remix version. Going to add it to the website too

**Comment by corydeppen** [comment]
According to the Remix [docs on remix.config.js](https://remix.run/docs/en/main/file-conventions/remix-config)...

> remix.config.js is only relevant when using the Classic Remix Compiler. When using Remix Vite, this file should not be present in your project. Instead, Remix configuration should be provided to the Remix plugin in your Vite config.

For Remix Vite projects, I'm wondering if using the `ssr.noExternal` option in the Vite config that's [mentioned in the docs](https://remix.run/docs/en/main/future/vite#esm--cjs) may be a possible solution.

**Comment by blvdmitry** [comment]
Totally, we've discussed this on X too with @muco-rolle and my latest (not yet pushed) example handles everything right besides a single compound component import issue that comes from the Next.js RSC requirements so got to find the right balance there before shipping this

**Comment by blvdmitry** [comment]
FormControl error should be gone now in 2.10.4 (more context and what was happening: https://x.com/markdalgleish/status/1770557434584785213?s=20)

**Comment by blvdmitry** [comment]
Updated the Remix example with Vite setup too
https://github.com/formaat-design/reshaped/tree/main/examples/starter-remix
