### ISSUE TITLE
Feature Request: Option to make Breadcrumbs spreader non-interactive

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#227]
**Is your feature request related to a problem? Please describe.**
Because of the way how I'm nesting things in my app, I'm experiencing a `<button>` within `<button>` nesting. That's not semantically correct and gets flagged as an error in the console.

**Describe the solution you'd like**
Possibly either a prop that will be passed to the spreader button individually, or setting `disabled={true}` (or similar) to the whole breadcrumbs component, essentially making everything non-interactive whilst setting the element of the spreader to non-button. Similar to below:

**Describe alternatives you've considered**
At the moment, (from the screenshot) I've set all the breadcrumbs to have `pointer-events: none;`. Which helps with making the whole thing non-interactive. However, this has nothing to do with the scope of the feature request. I'm only requesting for the option of the spreader not being a <button>.

**Additional context**
Here is my use case visually:
![image](https://github.com/formaat-design/reshaped/assets/9999658/c178d785-79f6-4a56-94f7-b99a91f5c632)

_Edit while I was testing this again:_
Thanks to [this change](https://github.com/formaat-design/reshaped/issues/222) I was able to set my `MenuItem` to `div` and have an easy fix, but I'll still leave this feature request, because there is a use case for some users where they don't want the spreader to be clickable. Maybe this should not be put in a priority list, or maybe if you think it's unnecessary feel free to delete!

**Comment by blvdmitry** [comment]
Great use case, will take a look for the next release

**Comment by blvdmitry** [comment]
Added a `disableExpland` flag in 2.10.3 which just renders an icon instead of the whole expand button. Docs will follow in the next minor release
