### ISSUE TITLE
Unable to switch color mode with useTheme when using SSR with generating themes

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#231]
**Describe the bug**
Unable to switch color mode with `useTheme()` when using SSR with generating themes.

**To Reproduce**
I used generating themes, and when using React, I can normally switch the color mode with `useTheme()`, but when using next.js, it doesn't work.

1. [React example](https://codesandbox.io/p/devbox/nifty-mclean-ctp7pj-forked-qkxymr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu42k8na00063b6i4jnnc3g8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu42k8na00023b6itqubx8m9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu42k8na00043b6i5pfnht27%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu42k8na00053b6iwgudq0kc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.06819353911447%252C35.931806460885525%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu42k8na00023b6itqubx8m9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42k8n900013b6i3135g15u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clu42k8na00023b6itqubx8m9%2522%252C%2522activeTabId%2522%253A%2522clu42k8n900013b6i3135g15u%2522%257D%252C%2522clu42k8na00053b6iwgudq0kc%2522%253A%257B%2522id%2522%253A%2522clu42k8na00053b6iwgudq0kc%2522%252C%2522activeTabId%2522%253A%2522clu42kkds00ay3b6i2nh8s3z1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clu42kkds00ay3b6i2nh8s3z1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clu42k8na00043b6i5pfnht27%2522%253A%257B%2522id%2522%253A%2522clu42k8na00043b6i5pfnht27%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42k8na00033b6ih63dnmx4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu42k91i000hdhf84pwy90zb%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clu42khfh00983b6is9mtqmyx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu42k8na00033b6ih63dnmx4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.97486535008977%257D)
2. [Next.js example](https://codesandbox.io/p/devbox/pensive-fermat-xrndck?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu42y8qi00073b6inoc0c8yf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu42y8qh00023b6iz1o2ek39%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu42y8qh00043b6i9buuadp8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu42y8qi00063b6i8ez7b5yy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu42y8qh00023b6iz1o2ek39%2522%253A%257B%2522id%2522%253A%2522clu42y8qh00023b6iz1o2ek39%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu42y8qi00063b6i8ez7b5yy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42y8qi00053b6igzjwt45y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu42y8qi00063b6i8ez7b5yy%2522%252C%2522activeTabId%2522%253A%2522clu42y8qi00053b6igzjwt45y%2522%257D%252C%2522clu42y8qh00043b6i9buuadp8%2522%253A%257B%2522id%2522%253A%2522clu42y8qh00043b6i9buuadp8%2522%252C%2522activeTabId%2522%253A%2522clu4349lb00s73b6h0j5ez70w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42y8qh00033b6iyl8gvjh2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu4349lb00s73b6h0j5ez70w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu4349ok0035dgfm5smuguvq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.987432675044886%257D)

**Environment:**
 - Version 2.10.6

**Comment by blvdmitry** [comment]
I think that might happen because Reshaped is defined in the root layout which is a server component in Next.js. That means that its JS code is not loading and it can't switch the value in the context when you use the hook. Can you try checking if moving the Reshaped provider to a client component helps in your case? 

https://reshaped.so/docs/getting-started/integrations/next#create-an-app-component

**Comment by hahahumble** [comment]
I tried to do it this way, but it still doesn't work.

[CodeSandbox: Moving the Reshaped provider to a client component](https://codesandbox.io/p/devbox/pensive-fermat-xrndck?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu42y8qi00073b6inoc0c8yf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu42y8qh00023b6iz1o2ek39%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu42y8qh00043b6i9buuadp8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu42y8qi00063b6i8ez7b5yy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu42y8qh00023b6iz1o2ek39%2522%253A%257B%2522id%2522%253A%2522clu42y8qh00023b6iz1o2ek39%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu42y8qi00063b6i8ez7b5yy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42y8qi00053b6igzjwt45y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu42y8qi00063b6i8ez7b5yy%2522%252C%2522activeTabId%2522%253A%2522clu42y8qi00053b6igzjwt45y%2522%257D%252C%2522clu42y8qh00043b6i9buuadp8%2522%253A%257B%2522id%2522%253A%2522clu42y8qh00043b6i9buuadp8%2522%252C%2522activeTabId%2522%253A%2522clu4349lb00s73b6h0j5ez70w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu42y8qh00033b6iyl8gvjh2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu4349lb00s73b6h0j5ez70w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu4349ok0035dgfm5smuguvq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.987432675044886%257D)

**Comment by blvdmitry** [comment]
One last thing: you have data attributes on both html and body tags. When you click on the theme switch, I see attributes updating on the html tag correctly but than body tag still overrides that back. Removing the from body should fix the issue I think

**Comment by hahahumble** [comment]
This will solve the problem 🎉

By the way, If I want to change the background color of a Button in dark mode, how should I do it? Or can dark mode use a different palette to generate theme?

This is my current configuration:
```js
const { generateThemeColors } = require("reshaped/themes");

const config = {
  themes: {
    productTheme: {
      color: generateThemeColors({
        primary: "#0891b2",
        critical: "#e22c2c",
        positive: "#118850",
        neutral: "#dfe2ea",
      }),
    },
  },
};

module.exports = config;
```

**Comment by blvdmitry** [comment]
Right now dark mode values are generated automatically and that was one of the ideas on the list to be implemented as a follow-up. Can you create a separate issue so I can track it in the product board for one of the upcoming releases?

**Comment by hahahumble** [comment]
Sure!
