### ISSUE TITLE
The theme color palette on the Reshaped homepage cannot be entered

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#233]
**Describe the bug**
The theme color palette on the Reshaped homepage cannot be entered.

**To Reproduce**
URL: https://reshaped.so/themes

**Additional context**
[Video recording](https://github.com/formaat-design/reshaped/assets/81009071/07654794-9c2f-4b60-aa51-c6c08de60a2a)

**Comment by blvdmitry** [comment]
Thanks, fixed it, rolling out later today 🙌 
It started failing due to the error thrown by the color generation function when passed hex is invalid


https://github.com/formaat-design/reshaped/assets/887379/d7cb0bb6-e850-4424-bee1-f00b046f669f
