### ISSUE TITLE
Tabs.Item has delayed transition

### ISSUE THREAD

**Issue by alexandertrefz** [formaat-design/reshaped#234]
**Describe the bug**
`<Tabs.Item>`s have a significantly delayed transition when hovering over them.

**To Reproduce**
It happens under all circumstances, it seems. It can be [seen on the official Documentation](https://reshaped.so/docs/components/tabs) as well.
Simply hover over any Tab.Item and watch the hover transition start delayed. Similarly the transition back to the normal state when one stops hovering is delayed.

**Expected behavior**
The hover transition should start playing immediately, like it does for buttons and all other hovers.

**Comment by blvdmitry** [comment]
Can you confirm if it's working for you in 2.10.10? 👀

**Comment by alexandertrefz** [comment]
Yes, fixed with 2.10.10 🎉
