### ISSUE TITLE
Button with type="submit" is not working as expected

### ISSUE THREAD

**Issue by petewins** [formaat-design/reshaped#235]
**Describe the bug**

Hi, I came across this problem when trying to submit a form using the keyboard

Button with type="submit" does not submit form when using keyboard

**To Reproduce**
```tsx
 <form onSubmit={(e) => { e.preventDefault();  alert("form submitted");}} > 
    <Button type="submit">
       Reshaped Submit Button
    </Button>

    <button type="submit">
      HTML Submit Button
    </button>
 </form>
```
1. focus on Reshaped button using keyboard
2. press the `enter` or `space` key

https://codesandbox.io/p/devbox/reshaped-button-on-enter-key-does-not-submit-form-8sprjr?file=%2Fapp%2Fpage.tsx%3A14%2C27

**Expected behavior**
Expect the form to submit. It looks like the button's onclick event is firing as expected but not the forms.

I'm not sure what the standards are for type="submit" button but I expect it to behave the same as a native html button

**Comment by blvdmitry** [comment]
Can you check if it works for you in 2.10.11?

**Comment by blvdmitry** [comment]
Oh yes, you're right. I haven't accounted for the use case when you use Button with a custom onClick that also submits the form natively

**Comment by blvdmitry** [comment]
Added that part in 2.10.12 as well

**Comment by petewins** [comment]
Thank you @blvdmitry, tested in 2.10.12 🔥
