### ISSUE TITLE
[Documentation] Minor improvements of the Vite installation guide 

### ISSUE THREAD

**Issue by molefrog** [formaat-design/reshaped#238]
First of all, Reshaped looks sick! Absolutely love its design and simplicity.

I've followed the Vite guide from the docs and there were some minor things I thought would be nice to have in the guide. It wasn't a big deal, but it could save up a couple of minutes for people who aren't familiar with Vite.

1. It seems like Vite [does not generate `postcss.config.js`](https://vitejs.dev/guide/features.html#postcss) by default, while the docs assume the file is already there.
2. The code for `App.tsx` doesn't contain a default export so a simple copy-and-paste won't work. Adding an extra line to that snippet could slightly improve the experience.

**Comment by blvdmitry** [comment]
Thanks for highlighting these, I'll update those bits in the Vite docs for the upcoming release 🙌

**Comment by blvdmitry** [comment]
Updated the content in the upcoming release planned for the next Monday
