### ISSUE TITLE
ActionBar - when elevated is set, pointer events are no longer working for its children

### ISSUE THREAD

**Issue by petewins** [formaat-design/reshaped#240]
**Describe the bug**
When ActionBar's elevated is set to true, I'm unable to interact with its children elements with the mouse. It is working as expected when its not enabled.

**To Reproduce**
```tsx
  <ActionBar elevated>
    <View direction="row" gap={4}>
      <View.Item columns={6}>
        <Button color="critical" variant="faded" fullWidth>
          Cancel
        </Button>
      </View.Item>
      <TextField name="email"/>
      <View.Item columns={6}>
        <Button color="primary" fullWidth>
          Confirm
        </Button>
      </View.Item>
    </View>
  </ActionBar>
```

**Expected behavior**
I expected `elevated` to be cosmetic, to only add shadow and that I'm still able to hover, click, etc. on its children elements

**Environment (please complete the following information):**
- MacOS
- Chrome
- 2.10.13

**Additional context**
- Keyboard navigation and interaction is still working as expected
- If children is wrapped with a View and ZIndex set, it works as expected again

**Comment by blvdmitry** [comment]
Thanks for reporting, it should work as expected in 2.10.16
