### ISSUE TITLE
Add Right Click Context Menu Component

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#241]
**Describe the solution you'd like**
Implement a right-click context menu component similar to the one described in the Shadcn UI documentation (https://ui.shadcn.com/docs/components/context-menu).

**Comment by blvdmitry** [comment]
To do:

- [ ] Unit tests
- [ ] Test inside scrollable containers

**Comment by blvdmitry** [comment]
Releasing in the next minor version 
https://bsky.app/profile/blvdmitry.me/post/3lcak3oe6wc2s
