### ISSUE TITLE
Allow Modal's to scroll on mobile devices

### ISSUE THREAD

**Issue by petewins** [formaat-design/reshaped#242]
**Is your feature request related to a problem? Please describe.**
On mobile, user's can't scroll up inside a modal, It seems they are able to scroll down but scrolling back up will trigger the modals swipe to close.

**Describe the solution you'd like**
Not sure what will be the ideal solution, but one thing that comes to mind is a prop to opt-out?

**Describe alternatives you've considered**
Might add an onMove `event.stopPropagation()` on my overflow container to temp prevent this behavior

example: Mobile devices currently can't scroll up, it closes the modal instead

https://github.com/formaat-design/reshaped/assets/19542805/42697aee-9bee-4d34-8e81-f83c1cd6cc8d

**Comment by blvdmitry** [comment]
Good point, I think it might be better to prevent swiping while scrolling is meant to happen first of all (can detect that based on the elements dimensions and scroll position). That should resolve the issue without opting-out manually with a prop

**Comment by blvdmitry** [comment]
Can you check if this works for you in 2.10.19? There already was partial handling of this use case which I forgot existed but it wasn't handling it correctly in some cases



https://github.com/formaat-design/reshaped/assets/887379/fdd29f6b-fda8-4da7-acb9-7778df086d14

**Comment by petewins** [comment]
@blvdmitry, works as expected now, thank you for a quick fix
