### ISSUE TITLE
Unexpected error when use a Fragment inside a View component

### ISSUE THREAD

**Issue by fschwalm** [formaat-design/reshaped#245]
**Describe the bug**
Unexpect error when use a Fragment inside a View component

**To Reproduce**
https://codesandbox.io/p/sandbox/radash-sandbox-forked-tsr2vh?file=%2Fsrc%2FApp.tsx

**Expected behavior**
Be possible use empty Fragment inside a View component

**Screenshots**
<img width="1618" alt="image" src="https://github.com/formaat-design/reshaped/assets/7445777/aa8adb02-3c70-4577-90a3-ba09baf9e221">

Thank you!

**Comment by blvdmitry** [comment]
Thanks for raising this, should be working in 2.11.4
