### ISSUE TITLE
New RichText/WYSIWYG field/input

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#248]
**Is your feature request related to a problem? Please describe.**
Not particularly a problem. We're rebuilding a major application from Kendo to Reshaped and we'll need a RichText editor at some point. Would be great if you consider it as an additional new component!

**Describe the solution you'd like**
A new RichText field/input component. Similar to [the Kendo UI one](https://www.telerik.com/kendo-react-ui/components/editor/), the one from [PrimeReact](https://primereact.org/editor/) or another simple one maybe?

**Describe alternatives you've considered**
An althernative would be another 3rd party library here.

**Additional context**
Might be a good idea to see if there are any open source solutions for this that can be integrated with Reshaped so you don't have to build the whole functionality from scratch?

**Comment by its-monotype** [comment]
You can try tiptap

**Comment by blvdmitry** [comment]
We likely won't be building a whole wysiwyg editor from scratch but we'll provide integration example for at least one existing wysiwyg library
