### ISSUE TITLE
Tabs component - crashes with "addHotKeys is not a function" error

### ISSUE THREAD

**Issue by ashwinibm** [formaat-design/reshaped#250]
**Describe the bug**
I run into a `addHotKeys is not a function` error when I use the Tabs component. 

**To Reproduce**
I'm using the example from the docs within my application. 
```
<Tabs>
  <Tabs.List>
    <Tabs.Item value="1">
      Item 1
    </Tabs.Item>
    <Tabs.Item value="2">
      Long item 2
    </Tabs.Item>
    <Tabs.Item value="3">
      Very long item 3
    </Tabs.Item>
  </Tabs.List>

  <Tabs.Panel value="1">Tab 1</Tabs.Panel>
  <Tabs.Panel value="2">Tab 2</Tabs.Panel>
  <Tabs.Panel value="3">Tab 3</Tabs.Panel>
</Tabs>
```

**Expected behavior**
Tabs should render.

**Screenshots**
<img width="1369" alt="Screenshot 2024-05-03 at 6 11 46 PM" src="https://github.com/formaat-design/reshaped/assets/2883006/24886593-931a-42d5-b7d4-a4c12c5d3a56">

**Environment (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Additional context**
A lot of the other Reshaped components render and seem to be working just fine in the same part of the application.

**Comment by blvdmitry** [comment]
Hi, can you make sure your application is wrapped with the Reshaped provider? It handles all hotkeys within the app so components relying on hotkeys are using its context

**Comment by ashwinibm** [comment]
> Hi, can you make sure your application is wrapped with the Reshaped provider? It handles all hotkeys within the app so components relying on hotkeys are using its context

This worked. Thank you!
