### ISSUE TITLE
Tooltips are displayed even when text is undefined

### ISSUE THREAD

**Issue by noob2** [formaat-design/reshaped#255]
**Describe the bug**
Tooltips are displayed even when text is undefined. Additionally, when I open a modal, the first tooltip is activated automatically.

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
[sandbox](https://codesandbox.io/p/sandbox/polished-lake-z5ljth?file=%2Fsrc%2FApp.tsx%3A14%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwaq3edd00062v6ijkndq067%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwaq3edd00022v6iyr9nnu5z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwaq3edd00032v6i4rlgt9mx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwaq3edd00052v6i70p3b1gh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.551755848037246%252C49.448244151962754%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwaq3edd00022v6iyr9nnu5z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwaq3edd00012v6ipoii4zt3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwaq89lm00022v6iy4z5m7p7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A5%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwaq3edd00022v6iyr9nnu5z%2522%252C%2522activeTabId%2522%253A%2522clwaq89lm00022v6iy4z5m7p7%2522%257D%252C%2522clwaq3edd00052v6i70p3b1gh%2522%253A%257B%2522id%2522%253A%2522clwaq3edd00052v6i70p3b1gh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwaq3edd00042v6iypzaml4b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwaq3edd00042v6iypzaml4b%2522%257D%252C%2522clwaq3edd00032v6i4rlgt9mx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwaq3edd00032v6i4rlgt9mx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
When text is undefined, empty string, or null, the tooltip should not be present on the screen.
When I open a modal, tooltips should not be visible until hovered over.

**Screenshots**
![image](https://github.com/formaat-design/reshaped/assets/12753796/72aef1fd-6769-47bf-be3e-a04e1089bf12)
![image](https://github.com/formaat-design/reshaped/assets/12753796/156dd811-c396-4580-bae4-a606f3d7cf2b)

**Environment:**
 - OS: Ubuntu
 - Browser: Google Chrome

P.S. I also noticed that ```<Tooltip text="hello" active={reactiveValue}>``` is not reactive.

**Comment by blvdmitry** [comment]
Regarding tooltips in the modal – this happens due to focus trapping since it the first focusable element inside the modal gets focused when it opens. What would be your expected behavior in that case? Would you expect the whole modal to get focused first as an "additional" element in the list of focusable elements or something else?

**Comment by blvdmitry** [comment]
Updated the `text` property implementation to support undefined values too. I think this became a side-effect of the latest react releases where ReactNode started supporting undefined values, while originally Tooltip wasn't supporting undefined

Also do you have a reproduction case for the reactivity part? When testing it locally based on the state – it seems to work as expected

https://github.com/formaat-design/reshaped/assets/887379/31e2924f-7d61-4202-844d-9eb88a11302b

**Comment by noob2** [comment]
@blvdmitry i woud expect that the modal is focused as additional element.I updated the [sandbox example](https://codesandbox.io/p/sandbox/polished-lake-z5ljth?file=%2Fsrc%2FApp.tsx%3A14%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwaq3edd00062v6ijkndq067%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwaq3edd00022v6iyr9nnu5z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwaq3edd00032v6i4rlgt9mx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwaq3edd00052v6i70p3b1gh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.01178027157004%252C52.98821972842996%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwaq3edd00022v6iyr9nnu5z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwaq3edd00012v6ipoii4zt3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwaq89lm00022v6iy4z5m7p7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A5%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwaq3edd00022v6iyr9nnu5z%2522%252C%2522activeTabId%2522%253A%2522clwaq89lm00022v6iy4z5m7p7%2522%257D%252C%2522clwaq3edd00052v6i70p3b1gh%2522%253A%257B%2522id%2522%253A%2522clwaq3edd00052v6i70p3b1gh%2522%252C%2522activeTabId%2522%253A%2522clwg2p7ip001d2v6icl3v8b7a%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clwg2p7ip001d2v6icl3v8b7a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwaq3edd00032v6i4rlgt9mx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwaq3edd00032v6i4rlgt9mx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to include the 3-rd case when using useResponsiveClientValue with 'active' property of the tooltip

**Comment by blvdmitry** [comment]
To keep you updated – this issue happens because of the implementation internals, where we rely on a multi-step state changes based on a reducer which trigger one after another in the react lifecycle. However media query changes happen based on the native event loop and we trigger some of the related reducer actions before React state gets updated. I'm planning to look into the positioning utility next and try to move as much logic as possible to sync vanilla js computations instead of waiting for useEffects to resolve in an attempt to address this.

**Comment by blvdmitry** [comment]
Actually found a simpler way to fix this even though it took some code refactoring just to understand the problem better. Going to resolve the modal bit tomorrow or the day after too and ship a new patch with this update

https://github.com/formaat-design/reshaped/assets/887379/a35bab83-5a05-4c32-9296-f8aa09e5e93e

**Comment by blvdmitry** [comment]
Tried multiple approaches and added a new `autoFocus={false}` prop for disabling the auto focus on the first element and move it to the modal root initially. Additionally added an explicit `ariaLabel` property to add a custom label inn case Modal.Title and Modal.Subtitle are not used for in the modal.

https://github.com/formaat-design/reshaped/assets/887379/cb875f06-c587-454f-86fd-3fb386ba2a76

You can try it out in 2.11.11 and feel free to reply here or in a new issue in case there are any other suggestions regarding this thread
