### ISSUE TITLE
Make font-weight and color responsive

### ISSUE THREAD

**Issue by randalmaia** [formaat-design/reshaped#256]
**Is your feature request related to a problem? Please describe.**

I'am frustrated when a try to change the font-weight and color between the breaktpoints

**Describe the solution you'd like**
Make color and font-weight attributes responsive like any others attributes.

**Comment by blvdmitry** [comment]
Hey @randalmaia, do you also have some screenshot of what you're building so we can better understand the use case and see if we need to support any other related functionality?

**Comment by blvdmitry** [comment]
Added responsive font-weight for now since it was originally a part of the variant property. Would be still great to see your use case for the responsive color to better understand the context. In case this is also no longer relevant – I'll close it for now when the next release comes out
