### ISSUE TITLE
Unable to use Modal/Overlay in a Web Component

### ISSUE THREAD

**Issue by erickcelio** [formaat-design/reshaped#260]
**Describe the bug**
When using ﻿reshaped inside a web component with shadow DOM, the Modal or Overlay is attached to the window root instead of the root of the web component. This can be problematic if the website using the web component doesn't have the ﻿reshaped CSS, and you want the CSS to be scoped within the web component, as this can cause issues.

**To Reproduce**
https://codesandbox.io/p/sandbox/reshaped-wc-modal-dc2swq

**Expected behavior**
When using a modal within a web component, the modal should be attached to the root of the shadow DOM or provided with an element reference to be attached.

**Environment (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 125.0.6422.113

**Comment by blvdmitry** [comment]
Todo:
- [ ] Support containerRef
- [ ] useScrollLock with custom ref
- [ ] Test in web component
- [ ] containerRef with transparentOverlay and scrollable container

**Comment by blvdmitry** [comment]
@erickcelio do you still have a working codesandbox link for this? Can't access it myself. I've added support for the `containerRef` property which lets you render modals inside a custom container, including shadow roots but would like to see your desired setup since it's a bit complicated to reproduce a proper shadow dom styling setup just for one component example

**Comment by erickcelio** [comment]
Try this one @blvdmitry [Codesandbox](https://codesandbox.io/p/sandbox/reshaped-wc-modal-dc2swq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwz4ag4000063b6i9jcuq3hs%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwz4ag4000023b6ixhxretgt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwz4ag4000033b6igegztluh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwz4ag4000053b6iz8chvzrb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwz4ag4000023b6ixhxretgt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwz4ag4000013b6i8l3qlrx8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A22%257D%255D%257D%252C%257B%2522id%2522%253A%2522clwz4n2ib00023b6imcxdlgs3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwz4ag4000023b6ixhxretgt%2522%252C%2522activeTabId%2522%253A%2522clwz4n2ib00023b6imcxdlgs3%2522%257D%252C%2522clwz4ag4000053b6iz8chvzrb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwz4ag4000043b6i8fuufnbc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwz4ag4000053b6iz8chvzrb%2522%252C%2522activeTabId%2522%253A%2522clwz4ag4000043b6i8fuufnbc%2522%257D%252C%2522clwz4ag4000033b6igegztluh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwz4ag4000033b6igegztluh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), I just had a similar issue with the tooltip but I'll investigate a bit more and I can open a new issue for that

**Comment by blvdmitry** [comment]
Seems to be working in 3.0.6 but I also need to update its positioning for the cases when it doesn't fit into the web component


![Image](https://github.com/user-attachments/assets/0971f77f-6f90-4f82-854c-9b804e251cde)

**Comment by blvdmitry** [comment]
Just realized this is probably not what you're trying to achieve and you would want a full-screen modal but rendered inside the shadow dom element?

**Comment by blvdmitry** [comment]
Fixed 😅

![Image](https://github.com/user-attachments/assets/71d2c0a5-b689-44cf-bc5d-acb023c1de0d)

**Comment by blvdmitry** [comment]
After testing it a bit more, I've decided to go with an approach of automatically detecting shadow root instead of requiring developers to always pass the containerRef themselves. I'm going to ship a beta version later to test it out in your setup too
