### ISSUE TITLE
How should we use ul and li tags?

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#262]
**Describe the bug**
Reshaped reset css is removing style for ul and li tags

`ol[class],ul[class] {
    list-style: none;
}`

I could not found on text docs how ul li should be made, and because of the reset, I have to use !important to be able to use tailwind

`<ul className="!list-disc p-4">`

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://codesandbox.io/s/reshaped-typescript-zj57hm

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by blvdmitry** [comment]
Thanks for raising this, I'm going to ship an update in 3.1.0 for this which will wrap all global reset styles with our `rs.reset` layer which should lower the reset styles specificity and have your tailwind styles work without `!important`
