### ISSUE TITLE
Hello, Invoice not received after the purchase 

### ISSUE THREAD

**Issue by victorjeman** [formaat-design/reshaped#264]
Hello, I'm sorry if this is not the place to open such an issue, was looking to solve this from my profile but I couldn't find a way to download the invoice and I also didn't receive any confirmation email after purchasing the product.

Thank you

**Comment by blvdmitry** [comment]
Hey, can you email us at hello@reshaped.so with the personal data you would like to include in the invoice? We'll generate one for you

**Comment by victorjeman** [comment]
Thank you very much for the response.I'll do that
