### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#265]
Hi,

amazing work on this library I totaly love the api in component library :).
Our design team have purchased the pro bundle to use it as a base of our design system.

**Is your feature request related to a problem? Please describe.**
Our applications are currently running on react 17, and we have noticed that in peerDependencies reshaped specifies react18.

**Describe the solution you'd like**
Is there any specific reason for that, would it be possible to support react17?

**Comment by blvdmitry** [comment]
Hey, the only React 18 API we're using in our components is useId which is primarily used for the accessibility id attributes. In case you're using our source and are ok with modifying that part – you can replace it with your own id generation function.  If that's not possible for any reason – we can discuss it together to see if there are any other approaches that would solve this for you

**Comment by mareksed** [comment]
Awesome thx for the quick response, love it, that should be good enough for us :).
