### ISSUE TITLE
Text field within MenuItem does not register " " (space) input.

### ISSUE THREAD

**Issue by ForrestCogna** [formaat-design/reshaped#266]
**Describe the bug**
Placing a TextField within MenuItem component prevents spaces from being registered. Example: "My text input" displays: "Mytextinput".

**To Reproduce**
Create an isolated reproduction on the CodeSandbox:
[Isolated reproduction on Codesandbox](https://codesandbox.io/p/sandbox/strange-frost-kd82mj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxx38dbh00063b6nug79g5ma%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxx38dbg00023b6npskc7uua%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxx38dbg00033b6n0gztxzlv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxx38dbg00053b6nve4wkh11%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxx38dbg00023b6npskc7uua%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxx38dbg00013b6nzwax7a7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxx38dbg00023b6npskc7uua%2522%252C%2522activeTabId%2522%253A%2522clxx38dbg00013b6nzwax7a7b%2522%257D%252C%2522clxx38dbg00053b6nve4wkh11%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxx38dbg00043b6n2zgrjual%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxx38dbg00053b6nve4wkh11%2522%252C%2522activeTabId%2522%253A%2522clxx38dbg00043b6n2zgrjual%2522%257D%252C%2522clxx38dbg00033b6n0gztxzlv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxx38dbg00033b6n0gztxzlv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
TextInput should register spaces even inside a MenuItem component

**Screenshots**

**Environment (please complete the following information):**
 - OS: iOS
 - Browser chrome/arc

**Additional context**
There is a workaround via:
```ts
<TextField
 inputAttributes={{
   onKeyDown: (e) => {
       if (e.key === ' ') {
         e.preventDefault()
         setValue((prev) => prev + ' ')
       }
    }
/>
```

**Comment by blvdmitry** [comment]
That's an interesting use case.  I think it ignores the space since space key would also trigger the button click. I'll see what we can do there to make sure it also doesn't trigger unexpected click events. Something that could help is learning more about the use case you're trying to solve with an input inside a clickable element 🙌

**Comment by ForrestCogna** [comment]
In this case, we have a MenuItem that can be renamed in-situ.

https://github.com/formaat-design/reshaped/assets/139330583/259fabcd-5e97-4888-aafb-b8ab4c4f6de0

**Comment by blvdmitry** [comment]
Started looking into it again and seems like it's now working in v3, including your codesandbox example if you upgrade Reshaped version there 😂

**Comment by ForrestCogna** [comment]
Nice! Thanks for looking into it
