### ISSUE TITLE
Vertical Slider

### ISSUE THREAD

**Issue by omgovich** [formaat-design/reshaped#267]
**Is your feature request related to a problem? Please describe.**
Our app has a vertical slider for selecting the thickness of a drawing tool.
At the moment Reshaped's `Slider` component can be horizontal only, so we can solve our task using the current version of the library.

I think this is a quite common task. For instance, you can find a lot of audio/video players with a vertical volume control.

**Describe the solution you'd like**
A new property changing the orientation of `Slider` similar to MUI:
https://mui.com/material-ui/react-slider/#vertical-sliders

**Describe alternatives you've considered**
We are using the native slider at the moment, but we are not sure it will look the same in all browsers.

**Comment by blvdmitry** [comment]
TODO:
- [ ] React implementation
- [ ] Prevent scrolling on touch move
- [ ] Unit tests
- [ ] Documentation
- [ ] Figma variant

**Comment by blvdmitry** [comment]
Got the first draft ready

https://github.com/formaat-design/reshaped/assets/887379/e6828dac-11f4-4a0d-87d3-2293a7f16c21

**Comment by omgovich** [comment]
Looks great)

**Comment by blvdmitry** [comment]
I have published 3.0.3 with the new `orientation="vertical"`. 
Documentation and design files will follow as a part of 3.1.0 release
