### ISSUE TITLE
Request: View's borderColor to support Responsive 

### ISSUE THREAD

**Issue by petewins** [formaat-design/reshaped#268]
**Is your feature request related to a problem? Please describe.**
<img width="601" alt="image" src="https://github.com/formaat-design/reshaped/assets/19542805/5d27d4ed-415d-4091-b678-6c1572890230">

**Describe the solution you'd like**
Hi, I would like a way to turn off borders for different view sizes. maybe something like this?
```ts
<View  borderColor={{s: undefined, m: 'neutral-faded', l: 'primary'}} />
```

Thanks

**Comment by blvdmitry** [comment]
Adding it for the upcoming release 🙌

https://github.com/user-attachments/assets/3bcd6b8f-e3d5-4fc2-880b-12c699176872
