### ISSUE TITLE
Is there an ETA for the v3?

### ISSUE THREAD

**Issue by abhagsain** [formaat-design/reshaped#269]
Hi, Dmitry
Is there a date for the v3 release? I was going to use your Figma v2, but then I saw that you're going to release a v3 soon, so I'm wondering if I should wait for the v3 or start with v2 and move to v3?

How difficult is the switch going to be?

**Comment by blvdmitry** [comment]
Hey, we're aiming for the week of 8th of July. If you're interested, send us an email and I can send you an early preview and a changelog with some migration notes

**Comment by abhagsain** [comment]
> Hey, we're aiming for the week of 8th of July. If you're interested, send us an email and I can send you an early preview and a changelog with some migration notes

Sent. Thanks 🫡
