### ISSUE TITLE
A way to disable a default touch interaction in Modal

### ISSUE THREAD

**Issue by omgovich** [formaat-design/reshaped#274]
**Is your feature request related to a problem? Please describe.**
We have a drag-and-drop feature inside of the popup that uses `modal`, but it conflicts with the swipe-down function used to close modals in Reshaped.

**Describe the solution you'd like**
A property to disable swipe interactions or a documented way to block it.

**Describe alternatives you've considered**
We solved that by adding `attributes={{ onTouchStart: e => e.stopPropagation() }}` to our drag-n-drop container.

**Comment by blvdmitry** [comment]
Should be available in 3.0.2 with `disableSwipeGesture` on `Modal` (and shipped `attributes.ref` support there as well). Documentation will follow as a part of 3.1.0
