### ISSUE TITLE
Unable to use Tooltip in a Web Component

### ISSUE THREAD

**Issue by erickcelio** [formaat-design/reshaped#275]
**Describe the bug**
When using ﻿reshaped inside a web component with shadow DOM, the Tooltip message is attached to the window root instead of the root of the web component. This can be problematic if the website using the web component doesn't have the ﻿reshaped CSS, and you want the CSS to be scoped within the web component, as this can cause issues.

**To Reproduce**
https://codesandbox.io/p/sandbox/reshaped-wc-tooltip-6ddsxh

**Expected behavior**
When using a tooltip within a web component, the text should be attached to the root of the shadow DOM or provided with an element reference to be attached.

**Environment (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 125.0.6422.113

Related to #260

**Comment by blvdmitry** [comment]
Hey, can you check if using `containerRef` in 3.0.4 helps you with this?

**Comment by blvdmitry** [comment]
TODO
- [ ] containerRef testing
- [ ] auto shadow root detection
- [ ] split containerRef and rendering boundaries

**Comment by blvdmitry** [comment]
Same as with the modal, I'm adding auto shadow root detection so tooltips, popovers, dropdown menus are automatically scoped within it. I don't have local setup to apply styles within shadow dom correctly right now so still got to test if position detection works as expected (I assume I'll need to add support for separating the containerRef and something like "boundaryRef")


![Image](https://github.com/user-attachments/assets/81fea097-0d1e-4c35-89a9-12f931aca4ba)

**Comment by blvdmitry** [comment]
Seems to be finally working ✨ Still hard to test locally and can't really write unit tests for this, but I've tested it here https://codesandbox.io/p/sandbox/reshaped-wc-modal-dc2swq and kept the implementation very minimalistic 😅 Planning to ship it in 3.1 over the weekend


![Image](https://github.com/user-attachments/assets/a7b61eac-dc76-4e81-8402-549c3ddaa59a)
