### ISSUE TITLE
Change the slider component

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#276]
**Is your feature request related to a problem? Please describe.**
I want to remove the slider render tooltip.

**Describe the solution you'd like**
Pass renderValue as null and doesn't render the tooltip at all

**Describe alternatives you've considered**
I am hacking using CSS to display none on the element.

**Additional context**
If possible, I would like to customize other things on the slider as well, like colors, sizes, and thickness, but the class name doesn't allow me to.

**Comment by blvdmitry** [comment]
Implemented it for the upcoming 3.1 release. The API is going to be `renderValue={false}` instead of null to align it with other similar properties in other components
