### ISSUE TITLE
[FEATURE REQUEST] Adding backdrop styling to modals and preventing overlay click

### ISSUE THREAD

**Issue by X86-7** [formaat-design/reshaped#279]
**Is your feature request related to a problem? Please describe.**
I have a scenario where I'd like to add a backdrop blur to a modal as it matches the style of our application more. It would also help prevent certain information from being visible while a modal is active until it has closed.

**Describe the solution you'd like**
This process could be done similar to how Chakra UI does it. 

`<Modal backdropFilter='blur(10px) /*any other CSS backdrop property*\'>Content</Modal>`

**Describe alternatives you've considered**
I have looked into how other design systems handle it, and while not every single design system does, it allows for more customization in how you design different scenes.

**Additional context**
On a side note, with a blurred overlay, you might want to provide the ability to prevent clicking outside the modal or hitting escape considering that some creators may use the blurred backdrop as a way to prevent data from being seen, such as premium features or showing users what to expect with a dashboard without actually showing the dashboard. Similar to the example I've provided below.

This could be done by adding an attribute such as `preventOverlayClick={true or false}` or something of the sort.

![DhPzE](https://github.com/user-attachments/assets/4445109f-652c-4ee2-8a0c-8c70b5303b9d)

**Comment by blvdmitry** [comment]
@X86-7 would an approach where blur value is predefined and can be enabled / disabled work for you? Seems like that can be an easier API and also possible to implement in Figma

**Comment by blvdmitry** [comment]
Meanwhile adding disableCloseOnOutsideClick to the release tomorrow

**Comment by X86-7** [comment]
> @X86-7 would an approach where blur value is predefined and can be enabled / disabled work for you? Seems like that can be an easier API and also possible to implement in Figma

Yes! Luckily for us that's fine! I didn't know if it would be easier to add something like this or just add an attribute.

**Comment by blvdmitry** [comment]
Adding for the release tomorrow

<img width="1172" alt="image" src="https://github.com/user-attachments/assets/4917af67-0de9-4162-bb3c-b456c6679d61">
