### ISSUE TITLE
New 3.0.1 generateThemeColors methods wrong values

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#283]
**Describe the bug**
The contrast values when generating the theme tokens are slightly different, but enough to make the theme text and look different

**To Reproduce**
We're only using a primary color:
`const colorsForOne3d = generateThemeColors({ primary: "#ff5100" });`

**Expected behavior**
Maybe tweak the calculations of `--rs-color-on-background-primary` only?

**Screenshots**
Old colors, before updating to Reshaped 3.0.1
![image](https://github.com/user-attachments/assets/a6180448-b37b-404f-a7f1-acf5f4399ce1)

New colors, after updating to Reshaped 3.0.1
![Pasted Graphic 1](https://github.com/user-attachments/assets/9fdbc277-a1e8-48d9-8fea-e90254b4f2a8)

**Additional context**
At the moment I've manually changed the `--rs-color-on-background-primary` from `#000000` to `#ffffff` in the theme css file

All this is done through updating our source code with the new 3.0.1 source code

**Comment by vladoyoung** [comment]
Also, I've noticed that you're doing 

```
		"./themes/reshaped/theme.css": "./dist/themes/reshaped/theme.css",
		"./themes/slate/theme.css": "./dist/themes/slate/theme.css",
		"./themes/figma/theme.css": "./dist/themes/figma/theme.css",
		"./themes/fragments/twitter/theme.css": "./dist/themes/fragments/twitter/theme.css",
```

in package.json exports. Do i need to add my newly generated themes in the source code here too?

**Comment by blvdmitry** [comment]
Hey, for the onColors – there are two approaches that products can use. Current WCAG approach (official one) and APCA (more human oriented but not adopted yet). Both have edge cases producing edge case results. So technically in v3 it's using WCAG and themes allow you to manually define the not fully accessible but better visually looking pairing and can potentially add a way to pick the contrast calc method on the theming level if that simplifies this for you. 

If you're publishing this as a package, you can add it to the package like you asked and I will look if I can have a better working wildcard approach

**Comment by vladoyoung** [comment]
I understand. Thanks for letting me know! I'll keep overriding the color token for now.

**Comment by blvdmitry** [comment]
Added a new option to pick the color contrast calculation approach everywhere you can define a theme. Adding some more docs and tests now, gonna ship it in 3.1


![Image](https://github.com/user-attachments/assets/b321e4b3-0cc1-477a-aaf7-2fa6cf82ae70)

![Image](https://github.com/user-attachments/assets/a3e65f94-fc4b-4b95-ad42-cb49d48ef6d5)

**Comment by blvdmitry** [comment]
Added docs and tests, so closing this issue
