### ISSUE TITLE
Multiple select?

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#285]
Hi,

We were wondering if you are considering implementing a multiple select component, similar to the following offered by MUI?

<img width="394" alt="Screenshot 2024-08-01 at 14 44 58" src="https://github.com/user-attachments/assets/20f02509-9b50-4b4a-8d49-9f3fb916a02d">

[https://mui.com/material-ui/react-select/#chip](https://mui.com/material-ui/react-select/#chip)

<img width="588" alt="Screenshot 2024-08-01 at 14 45 28" src="https://github.com/user-attachments/assets/00d713d4-f151-49a1-9243-cd988e6346c5">

[https://mui.com/material-ui/react-autocomplete/#multiple-values](https://mui.com/material-ui/react-autocomplete/#multiple-values)

We are wanting to add an invite users action to our app, similar to this one from notion for example, but not sure how to do it with reshaped components, without implementing our own combination of text area and badges 
<img width="391" alt="Screenshot 2024-08-01 at 14 48 30" src="https://github.com/user-attachments/assets/5426ed06-a82a-4241-ba92-dd963c81f819">

Thanks!

**Comment by blvdmitry** [comment]
Hey, yes, there is already a request planned for ~3.2
https://github.com/orgs/formaat-design/projects/2?pane=issue&itemId=62764493

**Comment by blvdmitry** [comment]
Gonna close this ticket as a duplicate
