### ISSUE TITLE
Importing types from Reshaped 3.0.1

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#287]
**Describe the bug**
`import { ToastProps } from '@our-reshaped-copy-from-source';` type doesn't include all types.

**To Reproduce**
The [default codesandbox](https://codesandbox.io/s/reshaped-typescript-zj57hm) from the bug report template doesn't work. It fails to load the resource.

**Expected behavior**
`timeout` and `position` being included in the types. Not sure if these are the only ones missing though. Maybe have a general look at the exported types? I've not experienced this with another component, but I assume it might happen when passing other components too.

**Screenshots**
A screenshot of the TS errors:
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/56446677-8619-4a73-be2d-8a1538a21497">

**Additional context**
Here's some example code:

```
import { ToastProps } from 'our-reshaped-copy-from-source'

export default async function updatePanorama(
	twinId: number,
	viewer: Viewer,
	show: (toast: ToastProps) => string,
	hide: (id: string) => void,
	panorama: Panorama
	) {
	const updateToast = show({
		text: 'Updating panorama position...',
		color: 'inverted',
		timeout: 0,
	});

```

**Comment by blvdmitry** [comment]
Technically it makes sense since timeout and position is not a part of the Toast component itself and only a part of the .show method which handles the rendering based on additional options. To make sure this is not breaking, I'll add an export with ToastShowProps, which will include additional options. Here is how they're used internally right now:

```
export type ShowOptions = { timeout?: Timeout; position?: Position };

type AddAction = {
	type: "add";
	payload: { toastProps: Props & ShowOptions; id: string };
};
```

**Comment by blvdmitry** [comment]
Ready for 3.1, releasing it over the coming weekend

![Image](https://github.com/user-attachments/assets/83be65b9-b24c-455c-8d7a-b9298f35b1f1)
