### ISSUE TITLE
Flyout onOpen handler is broken

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#289]
**Describe the bug**
when I open a popover I want to persist the index of selected color, or simply do some logic that is dependant on the some components state and/or props.
```
    const onOpen = () => {
        setEditingIndex(colors.indexOf(selectedColor?.toLowerCase()));
    };
```

this is not possible because the onOpen handler is not part of dependency array
```
	/**
	 * Component open/close handlers
	 * Called from the internal actions
	 */
	const handleOpen = React.useCallback(() => {
		const canOpen = !lockedRef.current && status === "idle";

		if (!canOpen) return;
		onOpen?.();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [status]);
```

**Comment by blvdmitry** [comment]
I have added a new `useHandlerRef` hook to memoize event handlers passed from props and applied it across all components where I was ignoring the deps array. Tested it in the flyout for now to make sure it works and will have to test it across all components that had a similar problem too.

Here is a code snippet if you need a temp workaround:

```
import React from "react";
import useIsomorphicLayoutEffect from "./useIsomorphicLayoutEffect";

const useHandlerRef = <T>(cb: T): React.RefObject<T> => {
	const ref = React.useRef(cb);

	useIsomorphicLayoutEffect(() => {
		ref.current = cb;
	});

	return ref;
};

export default useHandlerRef;
```

```
const { onOpen } = props;
const onOpenRef = useHandlerRef(onOpen);

React.useEffect(() => {
  onOpenRef.current?.();
}, [onOpenRef])
```
