### ISSUE TITLE
[FEATURE]: Modal customizable container

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#290]
**Is your feature request related to a problem? Please describe.**
Allow modals to render within containers.

similiar to how MUI and Antd design drawer works, you can supply container prop to render it within a specific dom element.

**Describe the solution you'd like**
Antd design drawer can be rendered like within the container.
See in examples
https://ant.design/components/drawer

**Describe alternatives you've considered**
as far as I understood the docs, modal and drawers can be only global

**Comment by blvdmitry** [comment]
Made some progress:

https://github.com/user-attachments/assets/319c4eff-4c88-40b2-983b-a245dd8e9778

todo: 
- [ ] Prevent horizontal scrollbar from appearing when modal is hiding / swiping
- [ ] Prevent the page scrolling whenever swiping the modal to close inside a container
- [ ] Check max-width handling inside a container

**Comment by blvdmitry** [comment]
All done, shipping in 3.2.0
