### ISSUE TITLE
"unlock" icon broken

### ISSUE THREAD

**Issue by Gmack786** [formaat-design/reshaped#292]
**Describe the bug**
Something is wrong w the vector for the unlock icon (v2.11), and only appears to be correct when size x6. 

**Additional context**
<img width="505" alt="Screenshot 2024-08-07 at 10 41 10" src="https://github.com/user-attachments/assets/f84fc997-7d64-4815-a29b-ef6307951d5d">

**Comment by blvdmitry** [comment]
This icon seems to be different from other icons in the feather icons library, so I've replaced it with a custom implementation that relies on the fill. Gonna include it in 3.1 on Monday

Before:

![Image](https://github.com/user-attachments/assets/9000e243-9fd7-4311-bec5-b133d18bd927)

After: 

![Image](https://github.com/user-attachments/assets/dd8236da-a5b9-4dcf-849e-3afa30b241c9)
