### ISSUE TITLE
useScrollLock throwing document is not defined

### ISSUE THREAD

**Issue by erickcelio** [formaat-design/reshaped#293]
**Describe the bug**
When using the `Modal` component in a Next.js app, receiving this error on the server: `Internal error: ReferenceError: document is not defined`

**Expected behavior**
Not facing an issue on this when pre-rendering on the server

**Screenshots**
<img width="1255" alt="Screenshot 2024-08-07 at 16 35 40" src="https://github.com/user-attachments/assets/feb8b4f5-ca7a-46c0-aaf4-3a81913f1dd4">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Arc
 - Version 1.52.0
 - Reshaped Version 3.0.9

**Additional context**
Looking at the `useScrollLock` code, probably moving the `const targetEl = document.body;` to be inside the `lockScroll` and `unlockScroll` solves this issue. I tried it locally here and it worked.

**Comment by blvdmitry** [comment]
Fixed in 3.0.10, thanks for reporting
