### ISSUE TITLE
`useScrollLock`breaks SSR

### ISSUE THREAD

**Issue by omgovich** [formaat-design/reshaped#294]
**Describe the bug**
`useScrollLock` is trying to access `document` right in its body and that breaks SSR. Here:

![CleanShot 2024-08-08 at 00 40 31@2x](https://github.com/user-attachments/assets/0185e9c1-84e5-4acd-b236-1faa37c0e34e)

**To Reproduce**
Use the hook in a Next.js project and you'll get this error:
![CleanShot 2024-08-08 at 00 43 51@2x](https://github.com/user-attachments/assets/016d23d1-c115-49dd-ab5a-1c2746bb4234)

**Expected behavior**
The hook accesses `document` in `useEffect` and doesn't break server rendering.

**Comment by blvdmitry** [comment]
Sorry for this one, gonna look into adding additional SSR testing environment before I can try it in the docs. Fix is out in 3.0.10
