### ISSUE TITLE
Is the Toast color 'warning' missing?

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#297]
**Describe the bug**
We've manually been adding the `warning` color type to the source code for the `Toast` component and it works out of the box. Why is the color missing from the documentation and missing in the types if the color works out of the box when added? Am I missing something here?

**Expected behavior**
Maybe add the option?

**Tweaked code**
`Toast.types.ts`
```
export type Props = {
	size?: "small" | "medium" | "large";
	icon?: IconProps["svg"];
	startSlot?: React.ReactNode;
	title?: React.ReactNode;
	text?: React.ReactNode;
	children?: React.ReactNode;
	actionsSlot?: React.ReactNode;
	color?: "neutral" | "primary" | "critical" | "warning" | "positive" | "inverted";
	className?: G.ClassName;
	attributes?: G.Attributes<"div">;
};
```

**Comment by blvdmitry** [comment]
I think it works because it uses View backgroundColor properties inside, while its was limited by the type definitions. If you have a use case where warning toasts are useful – we can definitely add support for it

**Comment by vladoyoung** [comment]
Yep, we are already using warning toasts in our project.

**Comment by blvdmitry** [comment]
Added for the next release ✨
