### ISSUE TITLE
How to set the default "rem" unit when generating the theme?

### ISSUE THREAD

**Issue by randalmaia** [formaat-design/reshaped#299]
**Is your feature request related to a problem? Please describe.**

In my theme font sizes are based in pixels, when I generate, reshaped replace for rem based in my pixels. 
How to set the default value for 'rem' in when I am generating the theme?

**Comment by blvdmitry** [comment]
Hi, can you provide a bit more context around what you're trying to achieve?
In our current implementation we're relying on the browser native implementation: browsers set the font-size to 16px by default and we're reducing the base font size to 14px (using percents) in the Reshaped provider. That way whenever you're picking a px size in your theme, we automatically convert it to a rem value based on the default 14px and all values you pick for your theme will automatically scale based on the browser settings

**Comment by randalmaia** [comment]
This is because I am using with tailwind css. 
In Tailwind the sizes are based in 16px = 1 rem. I want to follow the same for my reshaped theme

**Comment by blvdmitry** [comment]
Do you want to use default tailwind classes still for your development or would using our integration work for you in this case? https://reshaped.so/docs/getting-started/integrations/tailwind

**Comment by randalmaia** [comment]
I hae this integration set, it works but I want to have the same unit for rem in both. Reshaped components and tailwind classes.

For example: 
If I set in my theme the TEXT variant BODY-1 to `1 rem` this will be 14px 
But the when I add the class text-sm from tailwind that is 1 rem (will 14px because reshaped force it). But I expect it will be 16px

I need to sync this 'rem' between the libs

**Comment by erickcelio** [comment]
I was facing some issues with this too because we had some pages that already use a base font size of 16, and when we set our theme using pixels, you use a constant of 14. Maybe that could be something that we pass to generate the theme?
![image](https://github.com/user-attachments/assets/8f43844f-49ac-440e-9235-3c204b3bc02a)

**Comment by blvdmitry** [comment]
Makes sense, I guess I can adjust the default value to use 16px default as the default used by the browsers and also tailwind. Other option is to make it a configuration option for the reshaped.config.js to change the baseRem value to something else

**Comment by blvdmitry** [comment]
Updated the rems to calculate based on the 16px default while also kept the default body font-size equal to body3 font. Going to be out in the next release ✨
