### ISSUE TITLE
Tailwind overrides the reset styles applied by Reshaped on the html element starting from `reshaped@3.0.3`

### ISSUE THREAD

**Issue by its-monotype** [formaat-design/reshaped#301]
When using Tailwind with Reshaped, Tailwind styles have higher priority than Reshaped. As a result, Tailwind overrides all styles set to the HTML element by Reshaped.

**To Reproduce**
Download [tailwind integration example](https://github.com/formaat-design/reshaped/tree/main/examples/integration-tailwind) and update reshaped to 3.0.3.

**Expected behavior**
Reshaped styles have the highest priority.

**Screenshots**
![image](https://github.com/user-attachments/assets/041d8d0c-8c53-4589-9099-4dbbadc2deeb)

**Additional context**
I use Vite.
This issue exists only starting from `reshaped@3.0.3`.

**Comment by blvdmitry** [comment]
Let me think about it, the change in 3.0.3 was intentional to make sure custom product overrides take priority over the reshaped defaults but I will look into move some of the styles out of the rs.reset layer

**Comment by blvdmitry** [comment]
Actually, looking at the changes I have ready for the next patch, I have just moved out the font styles to the body and aligned the html font-size with the default browser one (also used in tailwind). Let me publish these changes in 3.1.4 and see if this helps in your case too

**Comment by blvdmitry** [comment]
You can try it in `3.2.0-canary.0`

**Comment by its-monotype** [comment]
Thank you, it’s working correctly now. However, all the text variants appear larger than they were before.

**Comment by its-monotype** [comment]
body-3 is now 16, body-2 ≈ 18, and body-1 ≈ 20 px. I think the body should range from 14-18 and a default of 16 px instead of 14 px is more common

**Comment by blvdmitry** [comment]
Are you using a custom theme there? You might need to regenerate it again to make sure rems are calculated based on 16px and not 14

**Comment by its-monotype** [comment]
Yes, I’m using a custom theme. Thanks for pointing that out! I’ve rebuilt it, and everything’s working perfectly now.

**Comment by its-monotype** [comment]
Now, even these tokens/values for each size look more rounded and clean. For example, instead of 4.571428571428571rem, it's now 4rem thanks to the use of 100%. Appreciate the improvements! 😀

**Comment by blvdmitry** [comment]
kudos to @randalmaia for opening https://github.com/formaat-design/reshaped/issues/299 😅
