### ISSUE TITLE
[Feature Request] OverlayProvider

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#305]
**Is your feature request related to a problem? Please describe.**
I'm building a custom overlay component that I can contain within a specified container because Overlay doesn't have a `<OverlayProvider>`

**Describe the solution you'd like**
It would be nice if we can get a provider to specify the position and bounds of the Overlay, similar to the [Toast](https://reshaped.so/docs/components/toast)

**Comment by vladoyoung** [comment]
Yeah, it's similar. Just like the ToastProvider limits the bounds, container and positioning of the Toast inside, I'm looking for something similar for the [Overlay](https://reshaped.so/docs/utilities/overlay) component

**Comment by blvdmitry** [comment]
Going to close this one as a duplicate, you can track the progress in the other mentioned ticket and it's going to be available in 3.2.0 ✨
