### ISSUE TITLE
[BUG] Switch Label is not disabled.

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#307]
**Describe the bug**
Switch label is not disabled

**To Reproduce**
https://codesandbox.io/p/sandbox/switch-bug-jfqwnp?file=%2Fsrc%2FApp.js%3A31%2C43

**Expected behavior**
Label should be disabled

**Environment (please complete the following information):**
 - Version 3.1.3

**Comment by blvdmitry** [comment]
Thanks for reporting, fixed for the next patch release

<img width="216" alt="image" src="https://github.com/user-attachments/assets/0a4a0a9b-b848-4560-a31c-0dbc476e0813">
