### ISSUE TITLE
[BUG] "mod" combinations from useHotkeys not working across different OS

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#309]
**Describe the bug**
We had a `"mod + enter"` / `"mod + Enter"` `useHotkeys` combination for some time in our app and we recently found out that it doesn't actually work on Linux (Ubuntu 24.04 LTS) and Windows (can't give you a specific version, but it was pretty much the same behaviour like on Linux). However, a combination like `"mod + z"` works fine across all OS.

**To Reproduce**
Not that a sandbox will really help, but the sandbox is still not working:
![image](https://github.com/user-attachments/assets/c9c8c843-7205-44b6-b240-c186baaeca17)

**Expected behavior**
Combinations to work across all OS

**Additional context**
I usually work on macOS and everything works just fine, but some colleagues experienced and tested the bug. As a temporary solution we've set our hotkey to just `Enter`. Unfortunately, I can't give you more testing information as it was difficult to test when I don't have a linux/windows machine. The issue appears to be coming from the keymap of the different OS keyboards and the events they send.

**Comment by blvdmitry** [comment]
Trying to reproduce this using the tools I have and for me the keydown event doesn't trigger at all for the Enter key, when pressing control + enter. Can you check if this also happens for you in this sandbox? https://codesandbox.io/p/sandbox/yt8v99

**Comment by blvdmitry** [comment]
nvm, that was a browserstack bug. Found the issue, this happens because I sort keys alphabetically and then for mod I replace mod with control / meta. So `enter+mod` becomes `enter+control`, while it should become `control+enter`

**Comment by blvdmitry** [comment]
Can you check if this works for you in 3.2.0-canary.6?

**Comment by vladoyoung** [comment]
I'm getting errors when installing `3.2.0-canary.6`. Maybe I'm doing something wrong in the `package.json` file?

https://codesandbox.io/p/sandbox/reshaped-popover-toggle-speed-reshaped-3-1-2-forked-l6nmx5

**Comment by blvdmitry** [comment]
You need something like this: https://codesandbox.io/p/sandbox/reshaped-usehotkeys-linux-test-forked-np76rr?workspaceId=5f69f060-a9f9-40f9-aefb-78d1547a1fc7

Since useHotkeys is using the context provided by Reshaped, so it has to be called inside the context render

**Comment by vladoyoung** [comment]
@blvdmitry can you check the sandbox's permissions again, please? It's saying "Sandbox not found"

**Comment by blvdmitry** [comment]
Can you try it again?

**Comment by vladoyoung** [comment]
Awesome job! Works on Ubuntu 24.04.1 LTS and Ubuntu 22.04.4 LTS!

One of my colleagues suggests that non-english key equivalents should work too, like `з` (`z`) (`mod + з` for example). Maybe a feature for a future version?

**Comment by blvdmitry** [comment]
Maybe, I'll keep this in mind. It's a bit more complicated to implement since there is no translated values in the event and probably we don't want to bloat the bundle size with all possible translations.
