### ISSUE TITLE
Modal Custom Portal Container

### ISSUE THREAD

**Issue by its-monotype** [formaat-design/reshaped#310]
Is it possible to specify a custom container for the modal? For example, something like this: https://www.radix-ui.com/primitives/docs/components/dialog#custom-portal-container

**Comment by blvdmitry** [comment]
Not yet but already planned for 3.2:
https://github.com/formaat-design/reshaped/issues/305
https://github.com/formaat-design/reshaped/issues/290

**Comment by blvdmitry** [comment]
Going to close this one as a duplicate, you can track the progress in the other mentioned ticket and it's going to be available in 3.2.0 ✨
