### ISSUE TITLE
Can't add `style` attribute to `Image`

### ISSUE THREAD

**Issue by omgovich** [formaat-design/reshaped#311]
**Describe the bug**

Passing `style` in `attributes` or `imageAttributes` has no effect.
The only values there are internal variables like `--rs-w-s: 300px; --rs-h-s: 200px;`

**To Reproduce**

https://codesandbox.io/p/sandbox/reshaped-image-bug-pq59mx

**Expected behavior**
Styles are added to `style` attributes

**Screenshots**

![CleanShot 2024-09-02 at 20 55 29@2x](https://github.com/user-attachments/assets/a64e970f-cdb3-4140-aa40-148cd72b8f05)

**Comment by blvdmitry** [comment]
Style was overridden by the Image before to define variables. Added for the next patch with `attributes={{ style: {} }}` and it will apply to all component states (image and all types of fallbacks)
