### ISSUE TITLE
[BUG] Popover de-focusing with TAB

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#313]
**Describe the bug**
Popover with `triggerType="hover"` that does not have a focusable element within the `Popover.Content`, do not de-focus/toggle off when toggled with tab focusing.

**To Reproduce**
https://codesandbox.io/p/sandbox/reshaped-image-bug-forked-v9mhj2

**Expected behavior**
The popover to be disabled if the focus is no longer on the trigger.

**Screenshots**
https://github.com/user-attachments/assets/ed65dc0d-8901-4337-bba4-788d6dac9932

**Comment by blvdmitry** [comment]
Fixed for the next patch
