### ISSUE TITLE
[BUG] Popover trigger speed

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#314]
**Describe the bug**
Newer versions of Reshaped have a slower `Popup` trigger compared to older ones.

**To Reproduce**
Reshaped 3.1.2 - https://codesandbox.io/p/sandbox/7h9q9f
Reshaped 2.10.19 - https://codesandbox.io/p/sandbox/reshaped-popover-toggle-speed-reshaped-3-1-2-forked-qcxwqk

**Expected behavior**
Either the old speed or to have control over the speed with a `triggerSpeed` attribute for example.

**Screenshots**
Reshaped 3.1.2:

https://github.com/user-attachments/assets/3d7974db-bd1e-47f2-9fdf-3f47565711d0

Reshaped 2.10.19:
https://github.com/user-attachments/assets/d0628c1f-6d97-4410-8140-ea09bac93600

**Comment by randalmaia** [comment]
I have the same issue

**Comment by omgovich** [comment]
+1 We are also considering using Popover with `triggerType="hover"` for header submenus, but at the moment the delay is too big for that.

**Comment by blvdmitry** [comment]
Looking at the current logic, does any of you have a requirement to actually control it or do you just expect that popovers will animate instantly? 

Currently, we already have a similar logic applied for submenus in dropdown menu which are displayed instantly and the current timer was implemented for the "flyout" groups which most of the time is used for tooltips. So I'm considering just controlling this internally, keeping tooltips as is and making popovers animate right away. Would that solve the problem?

**Comment by omgovich** [comment]
Works for us. We need delayed tooltips and instant popovers.

**Comment by blvdmitry** [comment]
Published in 3.2.0-canary.6

**Comment by omgovich** [comment]
Works like a charm
