### ISSUE TITLE
Charts and Data Grid Integration Guidelines

### ISSUE THREAD

**Issue by hahahumble** [formaat-design/reshaped#316]
**Describe the solution you'd like**
Hope to see integration guidelines for charts and data grids, specifically focusing on the integration of popular libraries such as shadcn/ui chart (https://ui.shadcn.com/docs/components/chart) and Tremor (https://tremor.so/). These guidelines should include the detailed instructions on aligning chart themes and colors with the Reshaped design system.

**Comment by blvdmitry** [comment]
Added documentation with code snippets for recharts (it's used internally for both shadcn and tremor) and tanstack table. In 3.3.0 I'm also planning to update documentation rendering which will allow me to add rendered examples right in the docs content as well
