### ISSUE TITLE
[Feature Request] Allow overriding styles like overflow property of the Modal component

### ISSUE THREAD

**Issue by ashwinibm** [formaat-design/reshaped#317]
**Is your feature request related to a problem? Please describe.**
We're seeing an issue when using the Modal with a 3rd party [select component](https://github.com/hc-oss/react-multi-select-component).
The select content gets clipped as you can see in the video. Its because of the `overflow: hidden` style on `--position-center` (in `Modal.module.css`).
I'm trying to override it with `<Modal active={show} onClose={onClose} attributes={{ style: { overflow: 'visible !important'} }}>` but its not taking effect. Seems to be because neither the `className` nor `style` passed from the user gets merged with the  styles defined within the Modal component.

**Describe the solution you'd like**
Merge the styles and classnames passed as props. This would give more flexibility in case we need to override not just the `overflow` attribute but other styles.

**Describe alternatives you've considered**
We're currently working around this by using an older Modal component. 

**Additional context**
Video showing the clipping issue:
https://github.com/user-attachments/assets/d00b4c73-f2d1-474f-a545-4167334edfbc

**Comment by blvdmitry** [comment]
Added `overflow="visible"` for the next patch release

<img width="505" alt="image" src="https://github.com/user-attachments/assets/b7476767-b84b-4bda-844a-63f4c5e09289">
