### ISSUE TITLE
`containerRef` is not available for `Tooltip` 

### ISSUE THREAD

**Issue by omgovich** [formaat-design/reshaped#318]
**Describe the bug**
Tho it is mentioned in the changelog that Tooltip supports `containerRef` since 3.1.2, it actually doesn't.
It is available for `Popover` and `DropdownMenu` only.

![image](https://github.com/user-attachments/assets/55f35e2a-ad6f-4481-8f2e-91f94aaf2ff0)

**Comment by blvdmitry** [comment]
Added for the next patch release
