### ISSUE TITLE
Icon width

### ISSUE THREAD

**Issue by its-monotype** [formaat-design/reshaped#322]
**Describe the bug**  
I'm trying to use the Icon utility with an icon library. Most icon libraries explicitly set the default width and height of the SVG to around 24px. However, when I attempt to set a custom size (e.g., `size={3}`), the height changes to 12px, but the width remains at 24px. The Icon utility seems to use `min-width: 100%` instead of `width`. Is this behavior intentional? It appears to be causing spacing issues.

**To Reproduce**  

1. Try to create a CodeSandbox reproduction:  
   [https://codesandbox.io/s/reshaped-typescript-zj57hm](https://codesandbox.io/s/reshaped-typescript-zj57hm)  
   
   *Note:* I encountered an issue while creating the sandbox—it says "Sandbox not found."

**Expected behavior**  
The width and height of the icon should adjust proportionally when setting a custom size. Both dimensions should be updated equally.

**Screenshots**  
If applicable, please find a screenshot below to illustrate the issue:  
![image](https://github.com/user-attachments/assets/f50f4854-c295-48bb-b30a-ee96aa8dbdce)

**Additional context**  
Workaround might be setting the `width` to `auto` on the SVG, like this:

```tsx
<Icon
  svg={<BookOpen size="auto" />}
  size={3}
  color="neutral-faded"
/>
```

However, this introduces extra boilerplate code.

**Comment by its-monotype** [comment]
Also it makes the icon-only button shape not ideally rectangular
![image](https://github.com/user-attachments/assets/e1e51176-c827-43d1-bc21-dcc8b24812f8)

**Comment by blvdmitry** [comment]
The styles are intentional but I think what happens is inline svg sizes override the internally defined height, causing the size to be incorrect. To fully understand the context: in your example, if you change the height of the svg css from `height: 100%` to `height: 100% !important`, does it get you to the desired behavior?

**Comment by blvdmitry** [comment]
Makes sense, I've added width: auto to the svg too to make sure it doesn't get overridden by the html attributes

**Comment by blvdmitry** [comment]
(I also checked and it seems the template on codesandbox was switched to private so I made it public again)

**Comment by omgovich** [comment]
Can confirm that this one is gone in v3.2
