### ISSUE TITLE
Allow for control of autofocus behaviour in popovers

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#323]
**Is your feature request related to a problem? Please describe.**

![CleanShot 2024-09-26 at 17 32 24](https://github.com/user-attachments/assets/ff5bd47a-8975-4965-8cf3-4c6983ef3064)

I am opening a popover with markdown editor built with lexical, I am using their auto focus plugin , but it gets overriden by auto focus from popover.

**Describe the solution you'd like**
Either allow passing a ref that should be focused or add flag to disable auto focus

**Describe alternatives you've considered**
wrote custom autofocus plugin that runs in setTimeout

**Additional context**
lexical autofocus plugin is nothing mystical just an useEffect that focuses an element passed in as ref.

**Comment by blvdmitry** [comment]
Seems like a valid use case for controlling this with props. I think passing the auto focus ref would be a better option indeed in this case to make sure the component still stays accessible and can also fully rely on full trap focus control internally to make sure there are no conflicts with the product code

**Comment by blvdmitry** [comment]
https://github.com/user-attachments/assets/31f32a07-6a7b-4971-89ad-a1b7a1bc4fd2

Adding to the next patch with the `initialFocusRef`
