### ISSUE TITLE
Flyout positioning breaks when trigger get outside of viewport on horizontal axes

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#325]
**Describe the bug**
Flyout positioning breaks when trigger get outside of viewport on horizontal axes

**To Reproduce**
todo

**Expected behavior**
same behaviour as on vertical axes

**Screenshots**
![CleanShot 2024-09-28 at 01 22 51](https://github.com/user-attachments/assets/7ee6aec1-02c5-41b2-aaca-1889b36708d8)

**Environment (please complete the following information):**
 - Version 3.0, 3.1.4(with fixed update position)

**Comment by mareksed** [comment]
@blvdmitry thx for picking this up so quickly.
I have also noticed that when moving on vertical axes and Popover gets repositioned.
it goes from 
`bottom-end` to `top-start`

shouldnt it be 
`bottom-end` to `top-end`

**Comment by blvdmitry** [comment]
Will take a look as well. Right now it doesn't exactly mirror it but uses a simpler fallback value system so definitely something I can improve

**Comment by blvdmitry** [comment]
By the way, loooking at the v axis behavior, would you expect the menu to stay on screen in the case when trigger goes outside of the viewport?

**Comment by mareksed** [comment]
That is a good question, it can very well be by usage what is correct I see 3 possible behaviours.

So from our PoV

1. Go out of viewport is what is expected

2. I can see an usecase for deactivate when not visible but that would require to test it with users
if it wouldnt feel too smart. We do not need an api to control such behaviour at this moment.

3. To force it into viewport seems unnatural.

**Comment by mareksed** [comment]
Wow free form has really nice solution for that
![Image](https://github.com/user-attachments/assets/5d4b2cda-ef25-463a-b571-eecf85b77b79)

Matching the behaviour of y-axis is enough, of you like it you can stash it for future ideas

**Comment by blvdmitry** [comment]
That's what I tried to describe 😅 You move the canvas same as before and flyout stays within the boundaries in case you move the trigger outside. I can definitely start by just solving your immediate request though 🙌

**Comment by mareksed** [comment]
Yeah but the timer which triggers animate out, is key ingredient making it feel natural. 
Also it feels it would fit well with reshaped well :)

**Comment by blvdmitry** [comment]
I believe it should work better in your case now and I've also improved smaller details in terms of how fallbacks get calculated. Going to ship this in the upcoming patch and I'll update the source code for it too. Gonna batch it with a few other requests.

https://github.com/user-attachments/assets/82d3f3cb-8d56-4e24-995f-4e43a1765d7f

**Comment by mareksed** [comment]
Sry for late response. 
You really played with it nicely :).
For us there would be an issue with repositioning from bottom to center start.
So as you are getting close to edge, changing bottom to bottom-end is great, but then the change to start is unecessary. it would most likely overlap our toolbar, we want to keep popover content around it.

**Comment by blvdmitry** [comment]
Hm, I was thinking about a similar thing regarding keeping the history of the previous position to keep it if there are no options that fit in the viewport instead of defaulting to the passed one. For what you mention I think I can also let you define which sides you want to pick from. 

There is already a `forcePosition` flag which is boolean, but maybe something like `forcePosition={['top', 'bottom']}` could be a good extension for advanced cases like yours?

**Comment by mareksed** [comment]
I am not sure I follow keeping the history of of the previous positions though, dont know what you mean.
But yes like being able to specify, how the fallback of position calculation behaves in the edge cases would be needed for us.

I assume that in your proposal forcePosition={['bottom-end', 'bottom', 'top-end', 'top']} would cover my use case in my example. So forcePosition would have two meanings, turn off the fallback mechanism or specify viable fallbacks?

**Comment by mareksed** [comment]
I like a property to modify fallback mechanism I think that is a nice solution.

How do you feel about those two meanings of forcePosition though, they are vastly different to me, one is turning off the fallback mechanism the other is modifying it. In general I am not fan of overriding property type it creates as much overload as a new one. Also forcePosition is singular what does passing an array of values to it means, feels like a stretch.
What about prop `fallbackPositions`

Btw would this be the same behaviour
`forcePosition={[]}`
`forcePosition={true}`

**Comment by mareksed** [comment]
So yes it would be the same then.
Only position prop being used, means forcePosition=true.

I let you meditate on the naming

**Comment by blvdmitry** [comment]
I ended up using `fallbackPositions` with the following options supported:
```
fallbackPositions={['top', 'bottom']}

// these are the same
fallbackPositions={[]}
fallbackPositions={false}
```

Also adding a deprecation comment for the `forcePosition` to make sure there are no 2 overlapping props starting from the next major version

**Comment by blvdmitry** [comment]
https://github.com/user-attachments/assets/47d3bedd-c8cd-4ec6-b347-2ff937bc2294

This should resolve the last part, adding it for the next patch

**Comment by marek-sdlk** [comment]
thank you @blvdmitry amazing work, can you make it available also as sources to download.

**Comment by blvdmitry** [comment]
Yes, I'm finishing Grid and your other request for a single observer and gonna ship it to the website then
