### ISSUE TITLE
[BUG] Text dynamic variant not working + useResponsiveClientValue ViewProps['variant'] missing

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#327]
**Describe the bug**
`<Text variant={{ s: "body-2", l: "body-1" }}>...</Text>` not working. I think in general dynamic values for variant are not working.

Also, there is no `ViewProps['variant']` option for types on `useResponsiveClientValue`

**To Reproduce**
https://codesandbox.io/p/sandbox/reshaped-usehotkeys-linux-test-forked-twy53f

**Expected behavior**
The `Text` component to work with the dynamic values and the `useResponsiveClientValue` to have the variant types

**Comment by blvdmitry** [comment]
Hm, for the hook, I think it's the same as something I've discussed recently in another issue, where hooks using context can't be called outside the Reshaped call. If you move it to another component rendered inside it – it should work fine. 

Regarding the same values through props – it might be something related to the sandbox setup and its postcss integration. Does the same happen for you in your project? Does this happen just in a few components or everywhere? I can't reproduce the same in the storybook but can try to figure out what's going on in your case

**Comment by vladoyoung** [comment]
Turns out we didn't set up the postcss properly on one of the new projects we have. Sorry for the panic, everything works properly now!
