### ISSUE TITLE
Grid Component

### ISSUE THREAD

**Issue by fschwalm** [formaat-design/reshaped#328]
**Is your feature request related to a problem? Please describe.**
Grid component supporting responsive props

**Describe the solution you'd like**
https://v2.chakra-ui.com/docs/components/grid/usage

**Describe alternatives you've considered**

```
const Stats = ({ children, ...viewProps }: ViewProps) => (
  <View
    grow
    attributes={{
      style: {
        display: 'grid',
        gridAutoFlow: 'column',
        gridTemplateColumns: 'minmax(min-content, 1fr)',
        gridAutoColumns: 'minmax(min-content, 1fr)',
        justifyItems: 'center',
        gap: '1rem',
      },
    }}
    {...viewProps}
  >
    {children}
  </View>
)
```

**Additional context**
I'd like use something like:

```
  <Grid
    gridAutoFlow={{s:'row',m:'column'}}
  >
    {children}
  </Grid>
  
```

  Thanks!

**Comment by erickcelio** [comment]
Really useful!

**Comment by JeromeDane** [comment]
This would really help. 🙏

**Comment by blvdmitry** [comment]
Ok, this seems to get some popularity really quick 😅 I will make sure to pick it for the upcoming minor release instead of some other internal plans

**Comment by blvdmitry** [comment]
Getting close to the first working implementation with the col/row span left. I've started with the simple grid implementation + most of the template related props + made all of it responsive. Anyone here who also needs auto flow grids right now? 

Also right now you will be need to use Grid.Item to assign style like grid-template-area, but I've also added a ticket for 3.3.0 to pick up css utilities that can be applied to any component.

```

export type Props<TagName extends keyof JSX.IntrinsicElements = "div"> = {
	gap?: G.Responsive<number>;
	rows?: G.Responsive<number | string>;
	columns?: G.Responsive<number | string>;
	areas?: G.Responsive<string[]>;
	children?: React.ReactNode;
	as?: TagName;
	className?: G.ClassName;
	attributes?: G.Attributes<TagName>;
};

export type ItemProps<TagName extends keyof JSX.IntrinsicElements = "div"> = {
	area?: string;
	colStart?: G.Responsive<number>;
	colEnd?: G.Responsive<number>;
	colSpan?: G.Responsive<number>;
	rowStart?: G.Responsive<number>;
	rowEnd?: G.Responsive<number>;
	rowSpan?: G.Responsive<number>;
	children?: React.ReactNode;
	as?: TagName;
	className?: G.ClassName;
	attributes?: G.Attributes<TagName>;
};
```

![Image](https://github.com/user-attachments/assets/64c1a75e-2c7b-4617-aae2-6f0c85771ce1)

**Comment by blvdmitry** [comment]
It's in a state matching everything you have originally used in the code snippet. Added `autoFlow`, `autoColumns`, `autoRows` as well as applied the same styling utility as the one used in View for `justify` and `align`. Shipping this in a patch in the next few days and docs will follow in the next minor release. Closing this meanwhile and moving to the "Waiting for the release" column.

Thanks again for the request 🫰

**Comment by fschwalm** [comment]
> It's in a state matching everything you have originally used in the code snippet. Added `autoFlow`, `autoColumns`, `autoRows` as well as applied the same styling utility as the one used in View for `justify` and `align`. Shipping this in a patch in the next few days and docs will follow in the next minor release. Closing this meanwhile and moving to the "Waiting for the release" column.
> 
> Thanks again for the request 🫰

Thank you @blvdmitry! I'm really excited to use it!
