### ISSUE TITLE
Add letter spacing to the design tokens for typography.

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#329]
**Is your feature request related to a problem? Please describe.**
I would like to add the letterSpacing to the configuration of the typography tokens.

**Describe the solution you'd like**
The same way we can define font-size and line-height I would like to define letter-spacing

**Describe alternatives you've considered**
I will create a text component myself that will incorporate the letter spacing on the configuration and use the text component under the hood

**Additional context**

**Comment by blvdmitry** [comment]
Hey there, this should be already available in the latest release: 
https://reshaped.so/docs/changelog#other-improvements

**Comment by vinizinmoraes** [comment]
Awesome thank you! I was on an older version.
