### ISSUE TITLE
AutoComplete support having Icon and startSlot value both set

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#331]
**Is your feature request related to a problem? Please describe.**
We have an icon on the left of our autocomplete, and we are using multiselect with badges.
The badges render before the Icon so as you select items it will push Icon further.

**Describe the solution you'd like**
Put Icon before the startSlot

**Describe alternatives you've considered**
not using icon

**Additional context**
![CleanShot 2024-10-15 at 21 31 17](https://github.com/user-attachments/assets/13663921-8118-435b-af4b-da406e1b0412)

**Comment by mareksed** [comment]
this might be closed after new autocomplete changes comming in 3.2

**Comment by blvdmitry** [comment]
I think your suggestion still makes sense here, so I'll keep it open for the next release

**Comment by blvdmitry** [comment]
Updated in code and in Figma (also found a minor spacing issue in the Figma library too)
