### ISSUE TITLE
Hover state on icon buttons is deforming icon

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#333]
**Describe the bug**
The hover state on safari is deforming icon

**To Reproduce**
open reshaped docs in safari

**Screenshots**

https://github.com/user-attachments/assets/04861746-d99f-4bb3-8ef2-e0c1cd0c3b57

**Environment (please complete the following information):**
 - OS: mac
 - Browser safari 18
 - Version 3.1.8

**Comment by blvdmitry** [comment]
Seems like a nasty edge case only reproducible in docs caused by the button highlighted layer transition. Fixed it with translateZ(0) for now and hopefully this layer will be gone soon with the wider color-mix support

**Comment by mareksed** [comment]
That is interesting, there is something similiar happening in our app, only on safari it might be related to our in app setup then.
I just checked it the same issue is on the page. 

So the fix is related to documentation page rather then component?

**Comment by mareksed** [comment]
Not only doc page, we had this behaviour in app on Safari.
But I could not simulate it on codesandbox. Added translateZ there helped when I tried it with dev console.

**Comment by blvdmitry** [comment]
Yeah, I think it's just an edge case caused by surroundings
