### ISSUE TITLE
Controlled Popover cannot be used with uncontrolled.

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#334]
**Describe the bug**
When using controlled and uncontrolled flyouts(popovers) they will get stuck on screen

**To Reproduce**
Storybook snippets for Flyout.stories.tsx.
```
const ControlledDemo = (props: any) => {
    const { position = "bottom-start", children, active, deactivate, activate, ...rest } = props;
    return (
        <Flyout disableCloseOnOutsideClick triggerType="click"
            position={position} {...rest}
            onOpen={activate}
            active={active}
            onClose={deactivate}>
            <Flyout.Trigger>
                {(attributes) => <Button attributes={attributes}>{position}</Button>}
            </Flyout.Trigger>
            <Flyout.Content>
                <div
                    style={{
                        background: "var(--rs-color-background-elevation-overlay)",
                        padding: "var(--rs-unit-x4)",
                        height: 150,
                        width: 160,
                        borderRadius: "var(--rs-radius-medium)",
                        border: "1px solid var(--rs-color-border-neutral-faded)",
                        boxSizing: "border-box",
                    }}
                >
                    {children || "Content"}
                </div>
            </Flyout.Content>
        </Flyout>
    );
};

export const positions = () => {
    const toggle1 = useToggle();
    const toggle2 = useToggle();

    return (
        <div style={{ paddingTop: 200 }}>
            <View gap={3} direction="row">
                <ControlledDemo position="bottom-start" {...toggle1} />
                <Demo position="bottom-end" />
                <Demo position="bottom" />

                <Demo position="top-start" {...toggle2} />
                <Demo position="top-end" />
                <Demo position="top" />

                <Demo position="end" />
                <Demo position="end-top" />
                <Demo position="end-bottom" />

                <Demo position="start" />
                <Demo position="start-top" />
                <Demo position="start-bottom" />
            </View>
        </div>
    )
};
```

**Expected behavior**
should work

**Screenshots**
![CleanShot 2024-10-18 at 10 00 17](https://github.com/user-attachments/assets/ae0d9797-dfe5-4ee7-9a7a-ecf5dfc9d02b)

**Environment (please complete the following information):**
 - Version 3.0, 3.1.8

**Comment by blvdmitry** [comment]
It might be true, I've tried out your exact code snippet and it works as expected in the same story. Can you try checking it again with 18 just inside the storybook whenever you have time?

**Comment by mareksed** [comment]
Weird I did check also with React.useId and it was also bugged.
The series of actions is opening the controlled flyout followed by uncontrolled, closing the uncontrolled after that the controllled one gets stuck.

Interesting will try to dig deeper, if you cannot reproduce feel free to close this.

**Comment by blvdmitry** [comment]
Maybe you can try reproducing the same in codesandbox? So far I've tried exactly what you have on the video, including hovering the buttons you did / moving the mouse outside of the storybook iframe and so on

**Comment by mareksed** [comment]
I will check it on the sources, that would be the best. If I reproduce I will go with sandbox.
I did not debug the the useIsDismissible yet but that is where it is failing.
So just eye balling it, the controlled flyout gets removed from the queue online 33. 

const addToQueue = (id: string, contentRef: Ref, triggerRef?: Ref) => {
	const parentItem = latestId ? queue[latestId] : undefined;
	const insideParent =
		triggerRef?.current &&
		parentItem &&
		parentItem.contentRef.current?.contains(triggerRef.current);

	if (!insideParent && triggerRef && latestId) {
		removeFromQueue(latestId);
	}

	queue[id] = { parentId: latestId, triggerRef, contentRef };
	latestId = id;
};
because it is not the parent, but it is still open.

**Comment by mareksed** [comment]
> Maybe you can try reproducing the same in codesandbox? So far I've tried exactly what you have on the video, including hovering the buttons you did / moving the mouse outside of the storybook iframe and so on

yeah that mouse movement of mine looks pretty drunk. Just open uncontrolled after controlled should have been enough

**Comment by mareksed** [comment]
Here is the codesandbox you are right that is faster.

https://codesandbox.io/p/sandbox/reshaped-typescript-zj57hm

**Comment by blvdmitry** [comment]
The link seems to be pointing to the template

**Comment by mareksed** [comment]
🤦 sry https://codesandbox.io/p/sandbox/hungry-shannon-nlgrq7

**Comment by blvdmitry** [comment]
Ah, I missed the `disableCloseOnOutsideClick` in your example

**Comment by mareksed** [comment]
Thought of a more real world usecase of two controlled popovers same issue.
https://codesandbox.io/p/sandbox/bold-mendeleev-rwwd5k

**Comment by blvdmitry** [comment]
Fixed and added a new story to test this behavior. It wasn't related to controlled/uncontrolled in the end but just to the combination of disableCloseOnOutsideClick and dismissibleQueue. Hoping to finish everything planned for the next minor this weekend so will publish it all together

https://github.com/user-attachments/assets/3b1dcf44-d172-4a1b-b949-4a877efaade1

**Comment by mareksed** [comment]
Awesome, yeah I have realised that the problem looked to be in dismissible relying on only one flyout hierarchy being open. I think the [second](https://codesandbox.io/p/sandbox/bold-mendeleev-rwwd5k) example is less silly than first one and is actually what we will be building in next weeks.

Just double check please that the second example works correctly.

**Comment by blvdmitry** [comment]
It works with your example too and that also led me to an idea of how to simplify the solution even further, so that was helpful, thanks
