### ISSUE TITLE
Modal onCloseComplete

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#345]
**Is your feature request related to a problem? Please describe.**
onClose handler runs immediately when closing event happens(at the start of the animation), I have some data that modal depends on and are only valid while modal is open.
I want to clean them onClose, but that is triggered before the animation finishes and it causes content shift in modal.

**Describe the solution you'd like**
add handler onCloseComplete that is triggered after closing transition is finished

**Describe alternatives you've considered**
We added timeout of 400ms that runs after deactivate call.

**Comment by blvdmitry** [comment]
Yes, absolutely

**Comment by blvdmitry** [comment]
Released in 3.2.7 with `onAfterOpen` and `onAfterClose`. Docs are coming with the next minor, updated source code is already on the website too
