### ISSUE TITLE
Table Row does not pass className attribute to component

### ISSUE THREAD

**Issue by tatemz** [formaat-design/reshaped#347]
**Describe the bug**

Passing `attributes={{ className: "foobar" }}` to the `Table.Row` component should ensure `foobar` is present on the `class` attribute of the `tr` element.

**To Reproduce**

```
<Table>
  <Table.Row attributes={{ className: "foobar" }}>
    <Table.Cell>Cell 1</Table.Cell>
    <Table.Cell>Cell 2</Table.Cell>
    <Table.Cell>Cell 3</Table.Cell>
  </Table.Row>
</Table>
```

https://codesandbox.io/p/sandbox/brave-browser-v798pf

**Expected behavior**

Passing a valid `className` to `attributes` prop should propagate it to the `tr` element

**Screenshots**
![Image](https://github.com/user-attachments/assets/f443ec56-8358-43e8-b32d-75fee53e192d)

**Environment (please complete the following information):**

**Additional context**

**Comment by blvdmitry** [comment]
Hey, thanks for bringing this up. Right now it's overridden by the default classNames and it's the only table compound component that misses a way to pass className as a prop so I've added it for the next patch. Going to release it early next week

**Comment by tatemz** [comment]
Thanks! I also noticed `Table.Cell` has the same behavior.

**Comment by blvdmitry** [comment]
Table.Cell does already support a `className` as a standalone prop but same as other components it overrides the attributes.className. Do you have a use case where className should be passed only through attributes?
