### ISSUE TITLE
Compatibility Issue Between Preact and Reshaped

### ISSUE THREAD

**Issue by JasonTanz** [formaat-design/reshaped#353]
**Describe the Bug**  
There is a compatibility issue between Preact and Reshaped, causing the `<Accordion />` component to not function as expected.

**To Reproduce**
- **Non-working Demo with Preact + Reshaped:**  
  [Preact Demo](https://stackblitz.com/edit/vitejs-vite-tkdn9u?file=src%2Fapp.jsx)

- **Working Demo with React + Reshaped:**  
  [React Demo](https://stackblitz.com/edit/vitejs-vite-unazw6?file=src%2FApp.jsx)

**Steps to Reproduce**
1. Go to the Code Sandbox demo.
2. Click to open the Accordion.
3. Click again on "Click to show"; an "Underneath" text should appear.
4. Observe the behavior:
   - **Preact Demo:** The "Underneath" text gets cut off.
   - **React Demo:** The "Underneath" text displays completely.

**Expected Behavior**  
In the React demo, the accordion adjusts its height automatically to fit the content, with smooth animations for opening and closing. However, in the Preact demo, the accordion height becomes fixed and any additional dynamic content will get cut off, and the animation breaks, resulting in a "jumping" effect when opening the accordion instead of a smooth transition.

**Screenshots**  
- **Broken Demo:**  
  ![Image](https://github.com/user-attachments/assets/23eb7aeb-4abd-4e19-ba81-8aae522beeb1)  
  - Accordion height is fixed.

- **Working Demo:**  
  ![Image](https://github.com/user-attachments/assets/cc625872-4775-4fb9-8906-8659ba396037)  
  - Accordion height adjusts automatically.

**Environment (please complete the following information):**
- **OS:** [e.g., iOS]
- **Browser:** [e.g., Chrome, Safari]
- **Version:** [e.g., 22]

**Comment by blvdmitry** [comment]
https://github.com/user-attachments/assets/c312d1a1-69d1-4788-ad82-ba195cce8d35

Moved it to a local setup and seems like an additional requestAnimationFrame in between the height calculations and switching to layoutEffect fixed the differences between react and preact. Shipping as a patch today
