### ISSUE TITLE
Grid.Items not respecting custom attributes prop

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#354]
**Describe the bug**
Attributes style doesnt work on Grid.Item component. If I add a classname with a tailwind class work as expected.

**To Reproduce**
You can use the reshaped grid component page and try to add custom style on the attributes prop. Example:

```
<Grid columns={{ s: 2, l: 3 }} gap={4} attributes={{ style: {background: "red"}}}>
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
  <View backgroundColor="neutral-faded" borderRadius="medium" height={10} />
</Grid>
```

**Expected behavior**
It should have a background red

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by blvdmitry** [comment]
Fixed it, I am passing custom css variables to style so it was overriding the attributes.style passed to the component. Going to release a patch tomorrow 🙌
