### ISSUE TITLE
Scrollbar size and position of `ScrollArea` component does not update as expected

### ISSUE THREAD

**Issue by danielroetzer** [formaat-design/reshaped#357]
**Describe the bug**
Scrollbar size and position does not update, when the content of the `ScrollArea` changes (e.g. items being added to a list).

Notes:
The scrollbar size does update, when the window is resized.
The position only updates, when you scroll.

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://codesandbox.io/p/sandbox/scrollbar-size-and-position-do-not-update-n86jgg

**Expected behavior**
I would expect that the scrollbar updates its position and size automatically, when the size of the children changes. This is a very common use case for infinite scroll or any form of lists, where the user can add/remove items.  I'd expect it to work similarly to how the Radix equivalent behaves.

**Screenshots**
In the screen recording below you can see the behaviour I am describing. I also added the [scroll area component from Radix](https://www.radix-ui.com/primitives/docs/components/scroll-area), so you have an easy comparison.

https://github.com/user-attachments/assets/e79a7229-04fa-4f76-b3ad-d3fc184c8f70

**Environment (please complete the following information):**
 - OS: Fedora 40
 - Browser: Reproduced in Firefox and Brave 
 - Version
   - Firefox: `132.0.1 (64-bit)`
   - Brave: `Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) unknown (64-bit)`

**Comment by blvdmitry** [comment]
Thanks for raising this, fix is coming in the next release

https://github.com/user-attachments/assets/9bf5ea7f-85df-40fb-8da6-fc7265b69b29
