### ISSUE TITLE
Trap focus is interfering with Popover Content

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#358]
**Describe the bug**
It seems like focus trap is always handling the focus even though it has been already handled by the rich text editor (lexical in this case)

**To Reproduce**
https://codesandbox.io/p/sandbox/interesting-ace-v4pnxc

the editor outside of the popover, the one inside popover will move focus to button inside popover.

**Expected behavior**
popover does not override behaviour of the content

https://github.com/user-attachments/assets/7f88f06a-e5de-4783-877b-ebe07e4f31c9

**Comment by blvdmitry** [comment]
Interesting use case, I think trap focus just doesn't include the div role="textbox" with contenteditable as a focusable element right now. I'm going to add it and test it out

**Comment by blvdmitry** [comment]
@mareksed followed your idea here and just checking for the defaultPrevented + added contenteditable into the focusable selector. Seems to be working fine in the new storybook example. Each time I focus the contenteditable element, I preventDefault 4 times and allow it to go through on 5th. Going to release in a patch tomorrow so you can test it out before the minor release if you want

https://github.com/user-attachments/assets/dec1f148-13a3-42bb-b5e2-66d1f4f95ef9
