### ISSUE TITLE
Add disabled state to DropdownMenu Subtrigger

### ISSUE THREAD

**Issue by marek-sdlk** [formaat-design/reshaped#359]
**Is your feature request related to a problem? Please describe.**
Cannot set disabled state on Subtrigger

**Describe the solution you'd like**
DropdownMenu.Subtrigger should have same disabled state as DropdownMenu.Item

**Describe alternatives you've considered**
DropdownMenu.Item disabled instead of DropdownMenu.Subtrigger.

**Comment by blvdmitry** [comment]
![Image](https://github.com/user-attachments/assets/d81f7c83-fb24-489d-9c2b-e65ecf2bedd3)

Added support for passing any properties supported by the dropdown menu items, besides the end slot and roundedCorners since they're predefined by the component. Shipping in the next release.
