### ISSUE TITLE
Scroll Area, better scroll position value

### ISSUE THREAD

**Issue by marek-sdlk** [formaat-design/reshaped#360]
**Is your feature request related to a problem? Please describe.**
We want to build infinite scroll, so would be great if we can get information about percentage of vertical scroll position from ScrollArea.

```
		const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
			const scrollableEl = scrollableRef.current;
			if (!scrollableEl) return;

			const next = {
				x: e.currentTarget.scrollLeft / scrollableEl.scrollWidth,
				y: e.currentTarget.scrollTop / scrollableEl.scrollHeight,
			};

			setScrollPosition(next);
			onScroll?.(next);
		};
```

the position in variable next that is returned from this handler is the value of top edge of the ScrollAreaBar.
I am not sure there is a use case for this value for consumer.

**Describe the solution you'd like**
Pass percentage of scrolled content.

https://codesandbox.io/p/sandbox/staging-snowflake-4kf2v4?file=%2Fsrc%2FApp.tsx%3A13%2C10

this should be 100% not 47%, but that is the position of the bar from the top.

 ![Image](https://github.com/user-attachments/assets/cf629c60-2ba1-47eb-866f-52fd5ee6bda0)

**Comment by blvdmitry** [comment]
Yes, this seems like a bug due to the variable being shared between the scroll thumb position and the arguments passed to the handler. Fixed it and shipping it tomorrow with a minor release

![Image](https://github.com/user-attachments/assets/7691307d-11d6-4bb5-8c15-b899680c26e7)
