### ISSUE TITLE
Responsive Syntax Fails to Resize Components: Width Always Stuck at 100%

### ISSUE THREAD

**Issue by IamSonOfTenny** [formaat-design/reshaped#361]
**Describe the bug**
The responsive syntax for sizing components in reshaped.so is not behaving as expected. Regardless of the screen size, the size property does not apply the appropriate value based on the specified breakpoints. Instead, it defaults to 100% width in all cases.

**Steps to Reproduce**
Use the following code snippet in a component:

`<View width="100%">
  <Modal
    size={{ s: '100%', m: '50%', l: '25%', xl: '20%' }}
    active={open}
    onClose={this.close}
    position="end"><div className="bg-rose-500">test new</div>
  </Modal>
</View>`

Test the component at various screen sizes (e.g., small, medium, large).

Observe the width of the Modal component.

**Expected behaviour**
The Modal component should resize dynamically based on the defined size property for each screen size:

s: 100%
m: 50%
l: 25%
xl: 20%

**Actual behaviour**
The Modal component always takes 100% width, regardless of the screen size.

**Screenshots**

![Image](https://github.com/user-attachments/assets/5f8edd38-a064-4d10-9e7e-316b34bc47b1)

**Environment (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome
 - Version: Latest

**Comment by blvdmitry** [comment]
Hey there, sorry for a long response 🙏

Can you share more details about your setup? This might be happening in case postcss config is either not imported from Reshaped or the configuration is passed incorrectly but depends on the framework/bundler you're using in your project.

Here is a video where I tried your example in our Storybook with an addition of a button to open the modal:

https://github.com/user-attachments/assets/7c92c0a3-e21f-47b2-b7bd-8cbaaacd65fb
