### ISSUE TITLE
Issues with nested `ScrollArea` components

### ISSUE THREAD

**Issue by danielroetzer** [formaat-design/reshaped#362]
**Describe the bug**
Nested `ScrollArea` components leads to buggy behaviour.

1. The scrollbar of nested scroll areas appear, when the parent scroll view is hovered.
2. Dynamically updated content of the nested scroll area leads to double scrollbars.

**To Reproduce**
https://codesandbox.io/p/sandbox/nested-scrollarea-issues-jp9j26

**Expected behavior**
1. Nested scroll areas should not show their scrollbar, when the parent scroll area is hovered.
2. Dynamically updated content of the nested scroll area should not lead to double scrollbars. It should retain a single scrollbar, which updates its size and position according to dynamic content updates.

**Screenshots**

https://github.com/user-attachments/assets/b9f54935-8d64-4d62-909f-38096b342a69

**Environment (please complete the following information):**
 - OS: Fedora 40
 - Browser: Reproduced in Firefox and Brave
 - Version
   - Firefox: `133.0.3 (64-bit)`
   - Brave: `Version 1.73.101 Chromium: 131.0.6778.139 (Official Build) unknown (64-bit)`

**Comment by blvdmitry** [comment]
Going to publish a patch and update the source later today

https://github.com/user-attachments/assets/2e5fc451-dc0e-474d-bf56-4eea2d4bc086

**Comment by blvdmitry** [comment]
Released and updated the source code link
