### ISSUE TITLE
Accordion configurator

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#94]
https://reshaped.so/content/docs/utilities/accordion

You're showing here one of your most powerful feature, in my opinion. Accordion + View. But the configurator is only supporting Accordion. Maybe you want to think about a way, to show in a better way the synergy?

**Comment by blvdmitry** [comment]
That's an interesting point, since it would be good to showcase as much as possible while also manage expectations correctly. IMO the more specific feature we show – the more people might also think that its design is quite opinionated. Going to look more into this

**Comment by blvdmitry** [comment]
After giving it another though - not planning to update this for now since configurator is not used that frequently to make it support such customisations yet. Might reconsider this in the future.
