### ISSUE TITLE
Turbopack

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#98]
Have you tried to use Reshaped with [Turbopack](https://turbo.build/pack)?

I was giving it a try after the new 13.1 update that supports now also [PostCSS](https://nextjs.org/blog/next-13-1#turbopack-improvements), but it seems Reshaped has still problems:

![image](https://user-images.githubusercontent.com/87228994/209682884-08569d52-e21e-4b3b-bc63-1d08e8fc9679.png)

![image](https://user-images.githubusercontent.com/87228994/209678487-34580b41-341f-4ee7-b089-4525020edf28.png)

**Comment by blvdmitry** [comment]
Not yet, since they're currently in alpha. I would expect some of the things to be fixed by the time they release either beta or RC, but if you have found an issue – I think the best we could now is open an issue in Turpoback repo

**Comment by mmailaender** [comment]
Created one: https://github.com/vercel/turbo/issues/3145 If you have some more detailed information, you maybe want to add them.
